var AccountLinkMenu=Backbone.View.extend({events:{"mouseleave":"handleOut","click a.deleteLink":"handleDeleteClick","click a.earlyExpireLink":"handleEarlyExpiredClick"},initialize:function(options){this.options=$.extend({},this.defaults,options);},remove:function(){this.trigger('removed');return AccountLinkMenu.__super__.remove.apply(this,arguments);},render:function(){var a;if(this.model.get('activeStatus')=='LIVE'){a=$('<a>').text('Early-Expire Link').addClass('earlyExpireLink');this.$el.append(a);}
a=$('<a>').text('Delete Link Record').addClass('deleteLink');this.$el.append(a);if(lockifyGlobals.debug){a=$('<a class="weblink-details" href="/account/link/'+this.model.get('publicId')+'" target="_blank">').html('Show ALL Details <span class="icon-out smallFont"></span><sup>&dagger;</sup>');this.$el.append(a);}
return this;},handleOut:function(){},handleDeleteClick:function(e){this.options.grid.trigger('deleteRowClick',[this.model]);this.remove();$('td').removeClass('menuOpen');},handleEarlyExpiredClick:function(e){this.options.grid.trigger('earlyExpiredRowClick',[this.model]);this.remove();$('td').removeClass('menuOpen');}});var AccountLinkActionListCell=Backgrid.Cell.extend({events:{"click .detailsLink":"handleDetailsClick"},initialize:function(options){AccountLinkActionListCell.__super__.initialize.apply(this,arguments);this.options=$.extend({},this.defaults,options);},render:function(){this.$el.empty();this.$el.addClass('handleCell');if(this.model.get('activeStatus')=="LIVE"){this.$el.addClass('activeLink');}
else{this.$el.removeClass('activeLink');}
var actionIcon=$("<div class='actionLink'><div class='icomoon-icon icon-handle'></div></div>");var detailIcon=$("<div class='icomoon-icon icon-plus detailsLink'></div>");_.bindAll(this,"handleActionOver","handleActionOut");this.$el.append(actionIcon);this.$el.append(detailIcon);this.$el.children('.actionLink').hoverIntent({over:this.handleActionOver,out:this.handleActionOut,timeout:300});return this;},handleDetailsClick:function(event){$(event.target).toggleClass('icon-plus icon-minus');this.column.attributes.grid.trigger('detailsRowClick',[this.model]);},handleActionOver:function(e){this.trigger('actionOver');var menu;menu=this.options.menu=new AccountLinkMenu({model:this.model,el:$('<div>').addClass('linkRowMenu'),grid:this.column.attributes.grid});this.$el.children('.actionLink').append(menu.render().el);this.listenTo(menu,'removed',function(){this.$el.trigger('mouseleave');});this.$el.addClass('menuOpen');},handleActionOut:function(e){this.options.menu.remove();this.$el.removeClass('menuOpen');}});var ActionsHeaderCell=Backgrid.HeaderCell.extend({initialize:function(){ActionsHeaderCell.__super__.initialize.apply(this,arguments);this.$el.addClass('actionsHeaderCell');}});var AccountLinkCell=Backgrid.Cell.extend({events:{"click .notificationsLink span":"handleNotificationsClick","click .editLabelLink":"handleEditLabelClick"},initialize:function(options){AccountLinkCell.__super__.initialize.apply(this,arguments);this.options=$.extend({},this.defaults,options);this.highlightProcessed=false;this.column.attributes.grid.on('highlightRow',_.bind(this.highlightRow,this));this.listenTo(this.model,"change:nickname",this.renderNickname);this.listenTo(this.model,"change:receiveNotifications",this.renderNotifications);this.listenTo(this.model,"change:activeStatus",this.renderStatus);},highlightRow:function(){var model=arguments[0][0];var publicId=this.model.get('publicId');if(publicId!=model.get('publicId')){return;}
var $row=this.$el;$row.addClass('highlightActive');$row.siblings().addClass('highlightActive');setTimeout(function(){$('.highlightActive').removeClass('highlightActive');},2500);},handleNotificationsClick:function(e){this.column.attributes.grid.trigger('notificationsRowClick',[this.model]);},renderNickname:function(){var nickname_value=this.model.get('nickname');var nickname=this.$el.find('.nickname');var html;if(typeof nickname_value!="undefined"&&nickname_value){html="Label: <span class='link editLabelLink'>"+nickname_value+"</a>";}else{html=" <span class='link editLabelLink'>Add Label</a>";}
nickname.show().html(html);},handleEditLabelClick:function(e){this.column.attributes.grid.trigger('editLabelRowClick',[this.model]);},renderNotifications:function(){if(this.model.get('activeStatus')=="LIVE"){text=this.model.get('receiveNotifications')?'Notifications: <span class="link">On</span>':'Notifications: <span class="link">Off</span>';}else{text=this.model.get('receiveNotifications')?'Notifications: On':'Notifications: Off';}
this.$el.find('.notificationsLink').html(text);},renderLinkAuth:function(){var authdetails;var authenticationType=this.model.get('authenticationType');switch(authenticationType){case'password':authdetails='Password';break;case'question':authdetails='Q&amp;A';break;case'twitter':authdetails='Twitter';break;case'email':authdetails='Email';break;case'gmail':authdetails='Gmail';break;case'native':authdetails='Lockify Account';break;case'phone':authdetails='Phone';break;default:authdetails='None';}
var text='ID Verification: '+authdetails;this.$el.find('.linkAuth').html(text);},renderStatus:function(){if(this.model.get('activeStatus')=="LIVE"){this.$el.addClass('activeLink');}
else{this.$el.removeClass('activeLink');this.$el.next().removeClass('activeLink');this.$el.find('.linkRemaining').hide();}
var text=this.model.get('activeStatus')+' <span class="wideOnly">&amp;</span><span class="narrowOnly"><br/></span> '+this.model.get('accessStatus');this.$el.find('.linkStatus').html(text);},render:function(){var linkhtml='';this.$el.html('');this.$el.addClass('descCell doubleLine string-cell');var publicId=this.model.get('publicId');this.$el.append($('<div>',{id:'linkId-'+publicId,class:'linkIdd',html:"<span class='rlb created'>Created: "+this.model.get('created')+"</span><span class='rlb linkid'>Link ID: "+publicId+'</span>'}));this.$el.append($('<div>',{class:'nickname'}));this.renderNickname();this.$el.append($('<div>',{class:'linkContent short',text:this.model.get('contentsStatus')}));this.$el.append($('<div>',{class:'linkAuth'}));this.renderLinkAuth();this.$el.append($('<div>',{class:'linkStatus'}));this.renderStatus();var $details=$('<div>',{class:'defaultHide linkDetails'});this.$el.append($details);var detailsView=new AccountLinkDetailsView({el:$details,model:this.model,grid:this.column.attributes.grid,commonModel:this.column.attributes.commonModel});return this;}});var AccountLinkEmptyRow=Backgrid.EmptyRow.extend({render:function(){this.$el.empty();var td=document.createElement("td");td.setAttribute("colspan",this.columns.length);$(td).append(_.result(this,"emptyText"));this.el.className="empty";this.el.appendChild(td);return this;}});var AccountLinkBody=Backgrid.Body.extend({_unshiftEmptyRowMayBe:function(){if(this.rows.length===0&&this.emptyText!=null){this.rows.unshift(new AccountLinkEmptyRow({emptyText:this.emptyText,columns:this.columns}));}}});var AccountLinkGridView=Backbone.View.extend({defaults:{actionCellClass:AccountLinkActionListCell,actionHeaderClass:ActionsHeaderCell,descriptionCellClass:AccountLinkCell},events:{"click #addMemberBtn":"handleAddBtnClick"},initialize:function(options){this.options=$.extend({},this.defaults,options||{});this.on('editLabelRowClick',this.editLabelRowClick);this.on('deleteRowClick',this.deleteRowClick);this.on('earlyExpiredRowClick',this.earlyExpiredRowClick);this.on('notificationsRowClick',this.notificationsRowClick);_.bindAll(this,'handleEmptyText');$("#sortGrid").imageDropdown({'selectList':$("#sortGrid_options"),'initialIndex':0,'initialValue':'none','showSelectedItemInList':true,'highlightClass':'li-hover'});defaultSortFunc=function(model,sortKey){return model.get(sortKey).toLowerCase();};var columns=[{name:"desc",label:"Description",sortable:false,editable:false,cell:this.options.descriptionCellClass,grid:this,commonModel:this.model},{name:"actions",label:"Actions",editable:false,sortable:false,headerCell:this.options.actionHeaderClass,cell:this.options.actionCellClass,grid:this}];var collection;if(window.location.search.match('nolinks')){collection=new Backbone.Collection();}else{collection=this.collection.fullCollection;}
this.grid=new Backgrid.Grid({columns:columns,collection:collection,body:AccountLinkBody,footer:Backgrid.Extension.Infinator.extend({scrollToTop:true}),emptyText:this.handleEmptyText});$('#accountLinksGrid').append(this.grid.render().$el);this.collection.fetch({reset:true}).then(_.bind(this.handleGridLoad,this));},handleEmptyText:function(){if(!window.location.search.match('nolinks')&&this.grid.collection.pageableCollection.clearing){return"<strong>Filter is in progress ...</strong>";}
if(!window.location.search.match('nolinks')&&this.grid.collection.pageableCollection.params.sSearch){$('#main').addClass('emptyFilter');return"<strong>No matching Link Records</strong><br/>Try changing or removing your filter entry.";}
if(window.location.search.match('nolinks')){$('#main').addClass('nolinks');}
return"<strong>You can track your Lockify Links here.</strong><br/>Currently, you don't have any. Make one by clicking <br class='wideOnly'/>&quot;Menu&quot; and then choosing <span class='rlb'>&quot;Make a Lockify Link.&quot;</span.";},handleGridLoad:function(){var hilightId=lockifyUtils.getUrlParam('hl');if(hilightId){lockifyUtils.hideLoadingCover();this.trigger('highlightRow',[this.collection.get(hilightId)]);}
try{var matches=lockifyUtils.getUrlPathname().match(/^\/account\/links\/(\w+)\/(action\/(\w*)\/)?/);var publicId=matches[1];var action=matches[3];var model=this.collection.get(publicId);if(model){var receiveNotifications=model.get('receiveNotifications');if(action=="set_notify_on"&&!receiveNotifications){this.trigger('notificationsRowClick',[model]);}
else if(action=="set_notify_off"&&receiveNotifications){model.once("changed:receiveNotifications",function(){$('.gridFilter').children('input').val(model.id).focus();$('.gridFilter input').trigger("keyup");$.when(model.fetchXhr,model.collection.fetchXhr).done(function(){lockifyUtils.hideLoadingCover();});},model);this.trigger('notificationsRowClick',[model]);$("#successChangeNotifyOff").dialog($.extend({},dialogOptions,{modal:false,dialogClass:"blip"}));setTimeout(function(){try{$("#successChangeNotifyOff").dialog('close');}catch(x){}},3500);}
this.listenTo(this.collection,"reset_fetch",function(){this.trigger('detailsRowClick',[model]);});}
$('.gridFilter').children('input').val(publicId).focus();$('.gridFilter input').trigger("keyup");$('.gridFilter').hide();$('.gridFilterBack').show();$('#refreshBtnContainer').hide();$('.gridNameTime').hide();$('.nicknameHelp').hide();lockifyUtils.hideLoadingCover();}catch(err){lockifyUtils.hideLoadingCover();}},handleAddBtnClick:function(e){this.trigger('addBtnClick');},editLabelRowClick:function(event){var model=arguments[0][0];var actionLabel=$('#nicknameDialog .dialogHeader .headerText span');if(model.get('nickname')){actionLabel.text(actionLabel.data('editText'));$("#btnDelNickname").show();}else{actionLabel.text(actionLabel.data('addText'));$('#newNickname').val('');$("#btnDelNickname").hide();}
var $nicknameDialog=$('#nicknameDialog');$nicknameDialog.data('triggerElemNew',$(this));$nicknameDialog.dialog(dialogOptions);$nicknameDialog.bind('dialogclose',function(){$('#nicknameContainer input.nickname').val('');});new NicknameView({el:$('#nicknameContainer'),model:model,saveBtnEl:$('.btnSaveNickname'),delBtnEl:$('#btnDelNickname'),cancelBtnEl:$('#btnNicknameCancel')});return false;},deleteRowClick:function(event){var model=arguments[0][0];var view=this;var publicId=model.get('publicId');if(event.stopPropagation){event.stopPropagation();}
else{event.cancelBubble=true;}
var deleteDialog=$("#deleteLinkDialog");deleteDialog.dialog(dialogOptions);if(model.get('activeStatus')=='LIVE'){$('.activeDeleteText').show();$('.expiredDeleteText').hide();}else{$('.expiredDeleteText').show();$('.activeDeleteText').hide();}
var btnDeleteNow=$("#btnDeleteLinkNow");btnDeleteNow.blur();btnDeleteNow.unbind('click').waitButton();btnDeleteNow.click(function(event){btnDeleteNow.addClass('loading');lockifyAjax.ajaxJSONSafe(lockifyEntryDeleteUrl,'public_id='+publicId,function(json){if(json.success){try{deleteDialog.dialog('close');}catch(x){}
var segs=$.grep(document.location.pathname.split("/"),function(n){return(n);});var redirect="";if(segs.slice(-1)[0]==publicId){redirect="/"+segs.slice(0,-1).join("/");$("#successDeleteDialog").find('.redirecting').removeClass('defaultHide').show();}
deleteDialog.bind('dialogclose',function(event){var sed=$("#successDeleteDialog").dialog($.extend({},dialogOptions,{modal:false,dialogClass:"blip"}));setTimeout(function(){try{sed.dialog('close');}catch(x){}
$("#deleteLinkDialog").unbind('dialogclose');$("#successDeleteDialog").find('.redirecting').hide();if(redirect){window.location=redirect;}},2500);});view.collection.remove(model);view.grid.render();view.model.set('count',view.model.get('count')-1);}else{try{$("#deleteLinkDialog").dialog('close');}catch(x){}
alert("Expiration Failed: "+json.Reason);}},function(req,textStatus,errorThrown){$("#divAdminInfo").append(req.responseText).show();});});},earlyExpiredRowClick:function(event){var model=arguments[0][0];var view=this;var publicId=model.get('publicId');$(this).qtip("hide");if(event.stopPropagation){event.stopPropagation();}
else{event.cancelBubble=true;}
var btnExpireLink=$("#btnExpireLinkNow");var expireLinkDialog=$("#expireLinkDialog");expireLinkDialog.dialog(dialogOptions);$("#btnAdminDelete").bind('keyup','return',function(){$("#btnAdminDelete").click();});btnExpireLink.blur();btnExpireLink.unbind('click').waitButton();btnExpireLink.click(function(event){btnExpireLink.addClass('loading');lockifyAjax.ajaxJSONSafe(lockifyManualExpireUrl,'public_id='+publicId,function(json){if(json.success){try{expireLinkDialog.dialog('close');}catch(x){}
expireLinkDialog.bind('dialogclose',function(event){var sed=$("#successExpireDialog").dialog($.extend({},dialogOptions,{modal:false,dialogClass:"blip"}));setTimeout(function(){try{sed.dialog('close');}catch(x){}
expireLinkDialog.unbind('dialogclose');},2500);btnExpireLink.trigger('deanimate');});btnExpireLink.removeClass('loading');model.set('activeStatus','EXPIRED (early-expired by you)');$('#linkId-'+publicId).siblings('.linkRemaining').hide();$('#linkId-'+publicId).parent().removeClass('activeLink');$('#linkId-'+publicId).parent().siblings().removeClass('activeLink');}else{try{expireLinkDialog.dialog('close');}catch(x){}
alert("Expiration Failed: "+json.Reason);}},function(req,textStatus,errorThrown){$("#divAdminInfo").append(req.responseText).show();});});},notificationsRowClick:function(event){var model=arguments[0][0];var oldValue=model.get('receiveNotifications');var value=!oldValue;model.set({receiveNotifications:value});var pickedFields=_.pick(model.attributes,'receiveNotifications','publicId');model.save(pickedFields,{patch:true,success:function(model,json){if(json.success){model.trigger('changed:receiveNotifications');}
else{alert("Change Failed: "+json.Reason);model.set({receiveNotifications:oldValue});}},error:function(model,json){model.set({receiveNotifications:oldValue});}});}});