var AccountLinksView=Backbone.View.extend({defaults:{gridViewClass:AccountLinkGridView},events:{"mouseenter #orgLogoBlock":'switchChangeBlock',"click .editTimezoneLink":"editTimeZoneDialog","click #setTimezoneBtn":"editTimeZoneSubmit","click .refreshBtn":"refreshButtonClick","keyup .gridFilter input":"filterInputKeyPressed","click #filterClear":"filterClearClick","click #filterClearLink":"filterClearClick"},initialize:function(options){this.options=$.extend({},this.defaults,options);this.timer=null;this.spanTimezone=this.$('.spanTimezone');this.changeTzDialog=this.$("#changeTzDialog");this.entryCollection=new EntryCollection();this.entryCollection.params={};this.gridView=new this.options.gridViewClass({collection:this.entryCollection,model:this.model});$(".filterSpiner").spinnerFont();this.entryCollection.on('sync',function(){$(".filterIcon").show();$(".filterSpiner").hide();});this.listenTo(this.entryCollection,"infinite-started",function(){$('.linksGridLoad').show();});this.listenTo(this.entryCollection,"infinite-finished",function(){$('.linksGridLoad').hide();});this.filterInput=$('.gridFilter input');$(".prependItem").click(function(){$(this).next('input').focus();});$(document).on("mouseover","#filterClear",function(){$(".gridFilter").addClass("clearHover");}).on("mouseout","#filterClear",function(){$(".gridFilter").removeClass("clearHover");});this.filterInput.on("focus",function(){$(".gridFilter").addClass("focus");}).on("blur",function(){if($(this).val()===''){$(".gridFilter").removeClass("focus");}});_.bindAll(this,['handleChange']);_.bindAll(this,['fadeInTzoneDefault']);this.model.bind('change',this.handleChange);this.model.fetch().done(_.bind(this.handleFetchSuccess,this));},filterInputKeyPressed:function(e){if(e.which>=35&&e.which<=40){return;}
var value=this.filterInput.val();if(value!==''){$(".filterIcon").hide();$(".filterSpiner").show();}
var view=this;clearTimeout(this.timer);this.timer=setTimeout(function(){$('.gridCount').hide();console.log("timeout "+value);var len=value.length;var collection=view.entryCollection;if(len===0){$('#filterClear').hide();}
else if(!$('#filterClear').is(':visible')){$('#filterClear').show();}
if(len!==0){collection.params['sSearch']=value;}else{delete collection.params['sSearch'];}
view.model.fetch_params(collection.params);collection.reset_fetch();$.when(view.model.fetchXhr,collection.fetchXhr).done(function(){$('.gridCount').show();});},100);},filterClearClick:function(){this.filterInput.val('');$('.gridFilter input').trigger("keyup");$(".gridFilter").removeClass("focus");},refreshButtonClick:function(){$('.refreshText').text('Refreshing');this.entryCollection.fetch().done(function(){$(".refreshText").text('Refreshed');setTimeout(function(){$(".refreshText").text('Refresh');},1000);});},handleFetchSuccess:function(){this.tzDropDown=new TimezoneSelectView({el:this.$('.timezoneViewWrapper'),model:this.model.set('timezone',this.model.get('timezone'))});this.tzDropDown.bind('change',this.fadeInTzoneDefault);},fadeInTzoneDefault:function(){if(this.tzDropDown.getSelectedOption().data('value')!=this.model.get('timezone')){$("#changeTzDefaults").removeClass('hidden');}else{$("#changeTzDefaults").addClass('hidden');}},handleChange:function(model){var count=model.get('count');var midText="";if(this.filterInput.val()!==''){midText=(count==1?" matches":" match");}
$('.gridCount').html(count+' <span class="wideOnly">Link</span> '+(count==1?"Record":"Records")+midText);if(count>0){$('#main').removeClass('emptyFilter');}
this.spanTimezone.text(model.get('timezoneDesc'));this.spanTimezone.data('timezone',model.get('timezone'));},editTimeZoneDialog:function(){this.changeTzDialog.dialog(dialogOptions);this.tzDropDown.setSelectedValue(this.spanTimezone.data('timezone').replace(/ /g,'_'));$("#changeTzDefaults").addClass('hidden');},editTimeZoneSubmit:function(){var selectedOption=this.tzDropDown.getSelectedOption();var timezone=selectedOption.data('value');this.model.set('timezone',timezone);this.model.set('timezoneDesc',selectedOption.text());this.entryCollection.params['timezone']=timezone;this.entryCollection.reset_fetch();try{this.changeTzDialog.dialog('close');}catch(x){}
if($('#saveTzDefaults').is(':checked')){var model=new GeneralSettingsModel();model.save({timezone:timezone},{success:function(){$('#saveTzDefaults').prop('checked',false);}});}
var view=this;this.changeTzDialog.bind('dialogclose',function(event){$("#successChangeTz").dialog($.extend({},dialogOptions,{modal:false,dialogClass:"blip"}));setTimeout(function(){try{$("#successChangeTz").dialog('close');}catch(x){}
view.changeTzDialog.unbind('dialogclose');},2500);});}});