var EntryModel=Backbone.Model.extend({defaults:{baseUrl:'',plaintext:'',msgLength:0,files:[],id:null,storeMessage:true,testError:0,nickname:'',lifeMinutes:null,maxViews:null,securityQuestion:null,securityAnswerHash:null,acceptCloseAnswers:null,password:null,passwordConfirm:null,max_userIds:1,userids:null,displayViews:null,displayTime:null,bitStrength:256,adminCredHash:null,enableEvents:null,easyCopy:true,easyPrint:true,allowManualExpiration:null,receiveNotifications:null,authMethod:null,authService:null,serviceURL:null,salt:null,publicId:null,showMoreOptions:null,specifyDecryptClientType:null,currentExpirationLimits:null},url:'/entry/patch',constructor:function(){_.bindAll(this,['getCipherText']);_.bindAll(this,['getHmac']);_.bindAll(this,['getCipherTextHmacUrlBase64']);Backbone.Model.apply(this,arguments);},clearAuthAttributes:function(){this.set({authMethod:'none',securityQuestion:null,securityAnswerHash:null,acceptcloseAnswers:null,password:null,passwordConfirm:null,userIds:null,authService:null,serviceURL:null});},expirationValuesMatchDefaults:function(defaults){if(!defaults)return true;return(this.get('maxViews')==defaults.get('maxViews')&&this.get('lifeMinutes')==defaults.get('lifeMinutes')&&this.get('allowManualExpiration')==defaults.get('allowManualExpiration'));},cryptoKeyLength:function(){return Math.ceil(this.get('bitStrength')/6);},maskedUserIds:function(){var self=this;var tokens;var all=$.map(this.get('userids'),function(userId){if(self.get('authMethod')==='thirdParty'){if(self.get('authService')==='google'){tokens=userId.split('@');return lockifyUtils.mask(tokens[0])+'@'+tokens.slice(1).join('');}else if(self.get('authService')==='twitter'){return lockifyUtils.mask(userId);}}else if(self.get('authMethod')==='phone'){var areaCode=lockifyUtils.mask(userId.slice(1,4),true,4);var exchange=lockifyUtils.mask(userId.slice(4,7),false);var number=lockifyUtils.mask(userId.slice(7),false);return areaCode+' - '+exchange+' - '+number;}else if($.inArray(self.get('authMethod'),['native','email','intEmail'])>-1){if(lockifyUtils.isEmail(userId)){tokens=userId.split('@');var name=tokens[0];var domain=tokens[1].split('.');return lockifyUtils.mask(name)+'@'+
$.map(domain,function(d){return lockifyUtils.mask(d);}).join('.');}else{return lockifyUtils.mask(userId);}}
return userId;});return $.grep(all,function(v,k){return $.inArray(v,all)===k;});},getCipherText:function(){var ct_hmac=this.get('cryptoAssets').ciphertext;return ct_hmac.substr(0,ct_hmac.length-45);},getHmac:function(){var ct_hmac=this.get('cryptoAssets').ciphertext;return ct_hmac.substr(-45);},getCipherTextHmacUrlBase64:function(){return lockifyCryptoUtils.base64ToURLBase64(this.get('cryptoAssets').ciphertext.replace(/\n/g,''));},createDataString:function(){var id=this.get('dataHash');var cryptoAssets=this.get('cryptoAssets');var dataStr;var boundary='---------------------------1504702169761927311267328916';var body='--'+boundary+'\r\n';body+='Content-Disposition: form-data; name="fields";\r\n\r\n';body+='id='+encodeURIComponent(id)+
(this.get('testError')?'&testError='+this.get('testError'):'')+'&nickname='+unescape(encodeURIComponent(this.get('nickname')||''))+'&lifeMinutes='+encodeURIComponent(this.get('lifeMinutes'))+'&maxViews='+encodeURIComponent(this.get('maxViews'))+'&maxAuthAttempts='+this.get('maxAuthAttempts')+'&securityQuestionAES256='+encodeURIComponent(this.get('securityQuestionAES256')||'')+'&securityAnswerHash='+encodeURIComponent(cryptoAssets.secAnHashes)+'&acceptCloseAnswers='+encodeURIComponent(cryptoAssets.secAnsAcceptClose)+'&pword='+encodeURIComponent(cryptoAssets.passwordHash)+'&userids='+encodeURIComponent(cryptoAssets.useridHashes)+'&useridsAES256='+encodeURIComponent(cryptoAssets.useridsAES256)+'&displayViews='+encodeURIComponent(this.get('displayViewsVals')||'')+'&displayTime='+encodeURIComponent(this.get('displayTimeVals')||'')+'&bitStrength='+this.get('bitStrength')+'&adminCredHash='+encodeURIComponent(cryptoAssets.adminCredHash)+'&enableEvents='+(this.get('enableEvents')?'true':'false')+'&easyCopy='+(this.get('easyCopy')?'true':'false')+'&easyPrint='+(this.get('easyPrint')?'true':'false')+'&allowManualExpire='+this.get('allowManualExpiration')+'&receiveNotifications='+this.get('receiveNotifications')+'&method='+encodeURIComponent(this.get('authMethod'))+'&service='+encodeURIComponent(this.get('authService')||'')+'&serviceURL='+encodeURIComponent(this.get('serviceURL')||'')+'&salt='+encodeURIComponent(cryptoAssets.salt)+'&msgLength='+(this.get('msgLength')>0?-1:0)+'&filesNumBytes='+encodeURIComponent(this.filesNumBytes())+'&fileNames='+encodeURIComponent(this.filenames())+'&showMoreOptions='+(typeof this.get('showMoreOptions')=='boolean'?this.get('showMoreOptions'):'')+'&specifyDecryptClientType='+(typeof this.get('specifyDecryptClientType')=='boolean'?this.get('specifyDecryptClientType'):'');body+='\r\n';body+='--'+boundary+'\r\n';body+='Content-Disposition: form-data; name="ciphertext"; filename="file.txt"\r\n';body+='Content-Type: application/octet-stream\r\n';body+='Content-Transfer-Encoding: base64 {}\r\n\r\n';body+=cryptoAssets.ciphertext+'\r\n';body+='--'+boundary+'--'+'\r\n';return body;},linkPrefix:function(){var baseURL=lockifyGlobals.linkUrl||(window.location.protocol+'//'+window.location.host+'/');return baseURL+'#';},encryptedURIComponentLengthFromByteCount:function(plaintextByteLength){var numBlocks=1+Math.ceil((plaintextByteLength+1)/16);return Math.ceil((numBlocks*128)/6);},totalDataLength:function(){var plaintextByteLength=lockifyCryptoUtils.encodeUTF8(this.get('plaintext')).length;fileMetadata=typeof this.gatherFileMetadata=='function'?this.gatherFileMetadata():null;if(fileMetadata){plaintextByteLength+=1;$.each(fileMetadata,function(index,item){var numBytes=item.numBytes?item.numBytes:item.size;plaintextByteLength+=lockifyCryptoUtils.encodeUTF8(item.filename).length+
1+
(''+numBytes).length+
1+
numBytes;});}
return this.encryptedURIComponentLengthFromByteCount(plaintextByteLength);},filesNumBytes:function(){var ret=[];fileMetadata=typeof this.gatherFileMetadata=='function'?this.gatherFileMetadata():null;if(fileMetadata){if(this.fileCollection.saveMetaData){$.map(fileMetadata,function(item,index){ret.push(item.numBytes?item.numBytes:item.size);});}else{$.map(fileMetadata,function(item,index){ret.push(-1);});}}
return ret.join('|');},totalDataLinkLength:function(){return this.linkPrefix().length+this.totalDataLength();},filenames:function(){var ret=[];fileMetadata=typeof this.gatherFileMetadata=='function'?this.gatherFileMetadata():null;if(fileMetadata){if(this.fileCollection.saveMetaData){$.map(fileMetadata,function(item,index){ret.push(item.filename);});}else{$.map(fileMetadata,function(item,index){ret.push("File_"+(index+1)+"_Name_Unknown");});}}
return ret.join('|');},getPayloadDescription:function(){var ret,pt,fs;ptl=this.get('plaintext').length;fsl=this.get('files').length;if(fsl==0&&typeof this.gatherFiles=='function'){this.set({'files':this.gatherFiles()});fsl=this.get('files').length;}
ret=ptl?"message":"";ret+=fsl?(ret.length?" and ":"")+"file":"";ret+=fsl>1?"s":"";return ret;},getPayloadItemCount:function(){var ret,pt,fs;ptl=this.get('plaintext').length;fsl=this.get('files').length;ret=ptl?1:0;ret+=fsl;return ret;},validateForEncryption:function(){var passedValidation=true;var authErrorOnly=null;var markFailure=function(type,msg){passedValidation=false;if(type=='plainInput'){authErrorOnly=false;}else if(authErrorOnly==null){authErrorOnly=true;}};this.bind('validationError',markFailure);if(!this.get('plaintext').replace(/[\s\t\n\u000B\f\r]/g,'').length||$('#data').val()=='Enter or paste your confidential message'){var noDataValMsg;if(typeof fileListView!='undefined'&&$('#incFileToggle').length){if(fileListView.fileCount()===0){noDataValMsg='Please add a message or file.';this.trigger('validationError','plainInput',noDataValMsg);$('#dataBottomBar').addClass('data-input-error');}}
else{noDataValMsg='Please add a message.';this.trigger('validationError','plainInput',noDataValMsg);}}
if(this.get('plaintext').length>$('#data').data('maxLength')){var overage=$('#dataCharCount').text().replace('-','');this.trigger('validationError','plainInput','Your message is too long by '+overage+' characters. Please shorten.');$('#dataBottomBar').removeClass('data-input-error');}
var invalidIDs;var userids;if(this.get('authMethod')=='password'){if(!this.get('password')&&!this.get('passwordConfirm')){this.trigger('validationError','authPassword','Please enter the password into both fields.');}
else if(!this.get('password')||!this.get('passwordConfirm')){this.trigger('validationError','authPassword','Please enter the password into both fields.');}
else if(this.get('password')!==this.get('passwordConfirm')){this.trigger('validationError','authPasswordConfirm','Your two passwords do not match. Please try again.'+(!$('#unmaskPword').is(':checked')?' Note that you can check "Show passwords" to see what you\'ve typed.':""));}}
else if(this.get('authMethod')=='question'){if(!this.get('securityQuestion')&&!this.get('securityAnswer')){this.trigger('validationError','secQuesBoth',"Enter both a question and an answer(s).");}else if(!this.get('securityQuestion')){this.trigger('validationError','secQues','Please enter a security question below.');}else if(!this.get('securityAnswer')){this.trigger('validationError','secAns','Please enter an answer(s) below.');}}
else if(this.get('authMethod')=='thirdParty'){if(!this.get('userids')||this.get('userids').length===0||this.get('userids')[0].length===0){if(this.get('authService')==='google'){this.trigger('validationError','google','Provide at least one Gmail address.');}else if(this.get('authService')==='twitter'){this.trigger('validationError','twitter','Provide at least one Twitter username.');}}else if(this.get('userids').length>this.get('max_userIds')){if(this.get('authService')==='google'){this.trigger('validationError','google',"You've entered "+this.get('userids').length+" Gmail addresses. Please limit yourself to "+this.get('max_userIds')+".");}else if(this.get('authService')==='twitter'){this.trigger('validationError','twitter',"You've entered "+this.get('userids').length+' Twitter IDs. Please limit yourself to '+this.get('max_userIds')+'.');}}
else{var requireGmailDotComDomain=true;var userIDRE={'google':(requireGmailDotComDomain?lockifyUtils.gmailRegex:lockifyUtils.emailRegex),'twitter':/^[A-Za-z0-9_]{1,15}$/}[this.get('authService')];invalidIDs=$.grep(this.get('userids'),function(userID){return!userID.match(userIDRE);});if(invalidIDs.length){if(this.get('userids').length==1){if(this.get('authService')==='google'){this.trigger('validationError','google','Gmail address is not valid.');}else if(this.get('authService')==='twitter'){this.trigger('validationError','twitter','Twitter username is not valid.');}}else{if(this.get('authService')==='google'){this.trigger('validationError','google',invalidIDs.length+' of the '+this.get('userids').length+' Gmail addresses '+(invalidIDs.length==1?'is':'are')+' not valid.');}else if(this.get('authService')==='twitter'){this.trigger('validationError','twitter',invalidIDs.length+' of the '+this.get('userids').length+' Twitter usernames '+(invalidIDs.length==1?'is':'are')+' not valid.');}}}}}
else if(this.get('authMethod')=='native'){if(!this.get('userids')||(this.get('userids').length===1&&this.get('userids')[0].length===0)){this.trigger('validationError','native','Provide at least one email address.');}else if(this.get('userids').length>this.get('max_userIds')){this.trigger('validationError','native',"You've entered "+this.get('userids').length+' Lockify usernames. Please limit yourself to '+this.get('max_userids')+'.');}else{invalidIDs=$.grep(this.get('userids'),lockifyUtils.isEmail,true);if(invalidIDs.length){if(this.get('userids').length==1){this.trigger('validationError','native','Email is not valid.');}
else{this.trigger('validationError','native',invalidIDs.length+' of the '+this.get('userids').length+' email addresses you entered '+(invalidIDs.length==1?'is':'are')+' not valid. Please enter valid emails of the form someone@example.com and resubmit. ');}}}}
else if(this.get('authMethod')=='phone'){userids=this.get('userids');if(!userids){this.trigger('validationError','phone','Enter a valid # in form 555-555-5555.',0);}
else{var model=this;$.each(userids,function(index,value){if(value.length!=11){model.trigger('validationError','phone','Enter a valid # in form 555-555-5555.',index);}
else if($.inArray(value.substr(1,3),$().validNorthAmericanAreaCodes())<0){model.trigger('validationError','phone','Please enter a phone number with a valid area code.',index);}});}}
else if($.inArray(this.get('authMethod'),['email','intEmail'])>-1){userids=this.get('userids');if(!userids){this.trigger('validationError','email','Provide at least one email address.',0);}else{invalidIDs=$.grep(this.get('userids'),function(userID){return!userID.match(lockifyUtils.emailRegex);});if(invalidIDs.length){if(this.get('userids').length==1){this.trigger('validationError','email','Email is not valid.');}else{this.trigger('validationError','email',invalidIDs.length+' of the '+this.get('userids').length+' emails '+(invalidIDs.length==1?'is':'are')+' not valid.');}}}}
else if(this.get('authMethod')!='none'){this.set({authMethod:'none'});}
if(authErrorOnly){this.trigger('authErrorOnly');}
return passedValidation;},encrypt:function(callback,encryption_type){if(typeof this!='undefined'&&this!=null&&typeof this.gatherFiles=='function'){this.set({'files':this.gatherFiles()});}
this.finalTotalDataLength=this.totalDataLength();var model=this;lockify.sjclBridge.encrypt.encryptData(this,encryption_type,function(cryptoAssets){var dataHash,authKey,key;if(!model.get('storeMessage')){cryptoAssets.ciphertext=getCipherTextHmacUrlBase64();authKey=lockifyCryptoUtils.hash_sha256_b64u(AUTH_KEY_CIPHERTEXT_HASH_PREFIX+cryptoAssets.ciphertext);dataHash=lockifyCryptoUtils.hash_sha256_b64u(cryptoAssets.ciphertext);key=cryptoAssets.key;}else{key=cryptoAssets.key;authKey=cryptoAssets.keyString;cryptoAssets.keyString=lockifyCryptoUtils.base64ToURLBase64(cryptoAssets.keyString);dataHash=lockifyCryptoUtils.hash_sha256_b64u(cryptoAssets.keyString);}
model.set({dataHash:dataHash,cryptoAssets:cryptoAssets,securityQuestionAES256:model.get('securityQuestion')?lockify.sjclBridge.encrypt.encrypts(model.get('securityQuestion'),authKey,key):null,outUrl:model.linkPrefix()+(model.get('storeMessage')?cryptoAssets.keyString:cryptoAssets.ciphertext)});if(typeof callback=='function'){callback();}});}});var EntryCollection=Backbone.PageableCollection.extend({model:EntryModel,url:"/account/links/data/",state:{pageSize:10},mode:"infinite",queryParams:{totalPages:null,totalRecords:null,sortKey:"sort"},clearing:false,fetchXhr:null,params:{},getNextPage:function(options){this.trigger("infinite-started");var self=this;return Backbone.PageableCollection.prototype.getNextPage.call(this,options).done(function(){self.trigger("infinite-finished");});},reset_fetch:function(){var url=this.url+"?"+$.param(this.params);if(this.fetchXhr&&this.fetchXhr.readyState>0&&this.fetchXhr.readyState<4){console.log(url+' - aborting previous fetch ');this.fetchXhr.abort();}
this.clearing=true;this.fullCollection.reset();this.clearing=false;this.links={'1':url};this.state.currentPage=1;var self=this;this.fetchXhr=this.fetch({url:url}).done(function(){console.log(url+' - fetch - done ');self.trigger('reset_fetch');});console.log(url+' - reset_fetch() finished ');return this.fetchXhr;}});