/***

 * Lockify Utils
 * Copyright 2010 Lockify Inc. All Rights Reserved.
 * License:
 * creates global variable and adding functions and variables like matching mask,
 * determining whether email is native or gmail etc

 * Extract the value of a URL query string parameter
 **/
var lockifyUtils={getUrlPathname:function(){return window.document.location.pathname;},getUrlParam:function(name,url){if(typeof url=="undefined"){url=window.location.href;}
var results=new RegExp('[\\?&]'+name+'=([^&#]*)').exec(url);if(!results){return 0;}
return results[1]||0;},isMobile:false,longValueLimit:200,cookiesEnabled:function(){var cookieName='testcookie';$.cookie(cookieName,true,{secure:document.location.protocol=="https:"?true:false});if($.cookie(cookieName)){$.cookie(cookieName,null,{secure:document.location.protocol=="https:"?true:false});return true;}else{return false;}},setupFixedDialog:function(event,ui){var adjust=function(){var dialogClass=$(event.target).dialog("option","dialogClass");if(!lockifyUtils.isMobile){$(event.target).dialog("option","dialogClass",dialogClass+" anim-in");$(event.target).dialog("option","hide","fade");}};adjust();},showMessageDialog:function(val,ms){if(typeof ms=="undefined"){ms=2500;}
var content=$('<div class="dialogContent"></div>').text(val);var dialog1=$('<div class="dialogContainer"></div>').append(content);var dialogOptions1=$.extend({},dialogOptions,{modal:false,dialogClass:"blip"});dialog1.dialog(dialogOptions1);setTimeout(function(args){try{dialog1.dialog('close');}catch(x){}},ms);},sanitize:function(val){return val.replace(/</g,String.fromCharCode(8249)).replace(/>/g,String.fromCharCode(8250));},emailRegex:/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i,emailChars:"@a-z0-9\d!#\$%&'\*\+\-\/=\?\^_`{\|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF\.",gmailRegex:/^[A-Za-z0-9\.\+_]{1,64}@gmail\.com$/i,isEmail:function(str){return new RegExp(lockifyUtils.emailRegex).test(str);},isGmail:function(str){return new RegExp(lockifyUtils.gmailRegex).test(str);},mask:function(str,exposeStart,minLength){if(minLength==null){minLength=2;}
if(str.length<minLength){return str.replace(/./g,'*');}
if(exposeStart==null){exposeStart=true;}
if(exposeStart){str=str.split('').reverse().join('');}
str=str.replace(/.(?!$)/gi,'*');if(exposeStart){str=str.split('').reverse().join('');}
return str;},isHtml5Enabled:function(){return typeof window.File=='function'&&typeof window.FileReader=='function'&&typeof window.FileList=='function'&&typeof window.Blob=='function';},isFlashInstalled:function(){if(typeof swfobject!=='undefined'){return swfobject.hasFlashPlayerVersion(lockifyIndexGlobals.minFlashReaderVersion);}else{return false;}},matchesMask:function(str,masks,matchPartial,caseSensitive){return lockifyUtils.matchesWhichMask(str,masks,matchPartial,caseSensitive)>-1;},matchesWhichMask:function(str,masks,matchPartial,caseSensitive){if(typeof matchPartial=='undefined'){matchPartial=false;}
if(typeof caseSensitive=='undefined'){caseSensitive=false;}
var matchIndex=-1;$.each(masks,function(i,mask){mask=mask.replace(/ /g,'');if(!matchPartial&&/^[0-9-*]{9,14}$/.test(mask)){mask=mask.replace(/[\-]/g,'');str=str.replace(/[^0-9]/g,'');}else{str=str.replace(new RegExp("[^"+lockifyUtils.emailChars+"]",'ig'),'');}
var origMaskLength=mask.length;if(matchPartial){mask=mask.substr(0,str.length);}else{mask+="$";}
mask=mask.replace(/\*/g,'\[^@\]');mask=mask.replace(/\./g,'\\.');var rg=new RegExp(mask,caseSensitive?"":"i");if(rg.test(str)){matchIndex=i;if(str.length==origMaskLength){return false;}}
return true;});return matchIndex;},endsWith:function(str,suffix){return str.indexOf(suffix,str.length-suffix.length)!==-1;},splitValueIntoSpans:function(str){var spans=$('<span></span>');$.each($.trim(str).split(' '),function(i,sub){spans.append($('<span>'+sub+'</span>'));});spans.children('span:even').addClass('remainingVal');spans.children('span:odd').addClass('remainingLbl');return spans.html();},onNewLinkPage:function(){return(typeof lockifyGlobals.linkUrl=='string'&&$("#output").length&&$("#output").text().match(lockifyGlobals.linkUrl));},onDecryptPage:function(){return(typeof lockifyGlobals.linkUrl=='string'&&window.location.href.match(lockifyGlobals.linkUrl));},numberWithCommas:function(x){return x.toString().replace(/\B(?=(?:\d{3})+(?!\d))/g,",");},isOnBeforeUnloadMsgSet:function(){try{return window.onbeforeunload!=null;}catch(e){if(typeof e=="string"&&e.indexOf("onbeforeunload is not available")!=-1){return false;}
throw e;}},setOnBeforeUnloadMsg:function(msg){if(typeof msg=="function"){msg=msg();}
lockifyUtils.beforeUnloadMsg=msg;try{if(typeof window.onbeforeunload=='undefined'){return;}
window.onbeforeunload=function(){if(lockifyUtils.beforeUnloadMsg!=null){return lockifyUtils.beforeUnloadMsg;}};}catch(e){if(typeof e=="string"&&e.indexOf("onbeforeunload is not available")!=-1){return;}
throw e;}},clearOnBeforeUnloadMsg:function(){try{window.onbeforeunload=null;}catch(e){if(typeof e=="string"&&e.indexOf("onbeforeunload is not available")!=-1){return;}
throw e;}},isAuthenticatedDom:function(){return $('.authenticatedUserOnly:visible').length>0;},hideLoadingCover:function(){$('#loadingCover').hide();if(Modernizr.cssanimations){$('#page').addClass('fadeIn');}else{$('#page').addClass('showIE');}},handleToggle:function(elem){if($(elem).hasClass('open')){$(elem).next(".toggleContent").toggleClass('open');$(elem).next(".toggleContent").slideToggle(function(){$(elem).toggleClass('open');});}else{$(elem).toggleClass('open');$(elem).next(".toggleContent").slideToggle(function(){$(elem).next(".toggleContent").toggleClass('open');});}
$(elem).children('.triggerOpen').toggle();$(elem).children('.triggerClose').toggle();},formatFileSize:function(byteCount,round){if(byteCount<0){return"";}
if(typeof round==='undefined'){round='ceil';}
var kb=Math[round](byteCount/1024,round),mb=null;if(kb>=1024){mb=Math[round](kb/1024*10,round)/10.0;}
if(mb){return mb+'MB';}else{return kb+'K';}},newWindow:function(url,width,height){var a=function(){if(!window.open(url,'t','scrollbars = yes, toolbar = 1, resizable = 1, status = 1, width = '+width+', height = '+height)){document.location.href=url;}};if(/Firefox/.test(navigator.userAgent)){setTimeout(a,0);}else{a();}},displayUpdateResultDialog:function(text,callback){$("#updateResultDialog").dialog($.extend({},dialogOptions,{modal:false,dialogClass:'blipSuccess',open:function(){$("#updateResultDialog").find(".resultMessage").text(text);setTimeout(function(){$("#updateResultDialog").dialog('close');},2500);},close:function(){if(callback)callback();}}));},displayUpdateResultInline:function(elem,text,isSuccess,callback){$(".preferenceChangeResult").remove();feedback=$('<span></span>');feedback.text(text);if(isSuccess){feedback.addClass('preferenceChangeResult success');}else{feedback.addClass('preferenceChangeResult error');}
feedback.insertAfter(elem).delay('1500').fadeOut('normal',function(){if(callback)callback();});},showDeletedMessage:function(json){$("#deletedDiv").show();$('.activeLink').hide();$("#deletedDiv").find("#deletedItem").text(json.serverStoredAsset=="ciphertext"?"encrypted data":"decryption key");if(($.browser["msie"]||navigator.userAgent.match('Chrome')!==null)&&window.location.href.length>2000){$("#ieTruncDialog").dialog($.extend({},dialogOptions,{closeOnEscape:false}));}
configAbuseForm();$("#validDiv").hide();},refreshBackgrounds:function(selector){$(selector).each(function(){var $this=$(this);if($this.css("background-image")){var oldBackgroundImage=$this.css("background-image");setTimeout(function(){$this.css("background-image",oldBackgroundImage);},1);}});},cssFadeIn:function(elem){$(elem).removeClass('hidden');},cssFadeOut:function(elem){$(elem).addClass('hidden');},setupQtips:function(sel,position,tipstyle,content,classes,showEvents){var defaultTipStyle={corner:'bottom center',border:0,width:10,height:10,offset:0};var defaultPosition={my:'bottom center',at:'top center',target:false,adjust:{x:0,y:0}};$.extend(defaultTipStyle,{"corner":$(sel).data('corner')});$.extend(defaultPosition,{"my":$(sel).data('my'),"at":$(sel).data('at'),"adjust":{"x":$(sel).data('x'),"y":$(sel).data('y')}});var defaultContent={text:$(sel).next().html()};if(typeof tipstyle=="undefined"||!tipstyle){tipstyle={};}
if(typeof position=="undefined"||!position){position={};}
if(typeof content=="undefined"||!content){content={};}
if(typeof showEvents=="undefined"||showEvents===null){showEvents='mouseenter';}
var defaultClasses={classes:''};tipstyle=$.extend(defaultTipStyle,tipstyle);position=$.extend(defaultPosition,position);content=$.extend(defaultContent,content);classes=$.extend(defaultClasses,classes);$(sel).qtip({content:content,position:position,show:{solo:true,event:showEvents},hide:{delay:300,fixed:true},events:{render:function(event,api){var elem=api.elements.tip;},show:function(event,api){api.elements.target.one('click',function(){api.set('hide.event','unfocus');});},hide:function(event,api){api.set('hide.event','mouseleave');}},style:{tip:tipstyle}});},print:function(){window.print();}};