/*
 * Lockify Base
 * Copyright 2010 Lockify Inc. All Rights Reserved.
 * License:
 * Contains functions for formatting file size, ajax methods and
 * intializes views required for chrome promos, feedback tab functions
 * setting up tooltips

*/
var lockify={gateway:{},acctLink:{},index:{},account:{},diag:{},gatewayFiles:{},manuals:{}};if(document.location.pathname==="/d"&&document.location.hash===""){window.location.href="/d-nodata";}
var dialogOptions={hide:null,show:null,bgiframe:false,minHeight:0,modal:true,resizable:false,width:500,position:[0,'top'],create:function(event,ui){lockifyUtils.setupFixedDialog(event,ui);$('.qtip:visible').hide();$('.dialogContent .defaultHide:visible').hide();$('.icon-help').removeClass('open');if(!$(this).parent().hasClass('coexist')){$('.ui-dialog-content:visible').dialog('close');}},beforeClose:function(event,ui){$(this).parent().removeClass('anim-in');},close:function(event,ui){var content=$(event.target).find('.dialogContent').eq(0);content.find('input:not(.keepAlive)').val('');content.find('textarea:not(.keepAlive)').val('');content.find('.error:not(.keepAlive)').text('');content.find('input[type=checkbox]').prop('checked',false);content.find('.tooltip-inline-content').hide();content.find('.validationError').removeClass('validationError');content.find('.cssFader').addClass('hidden');$(this).dialog('destroy');$('.button').trigger('deanimate');},focus:function(event,ui){$(this).find('button').blur();}};$(document).ajaxSend(function(event,xhr,settings){if(typeof lockifyGlobals.linkUrl!='undefined'&&window.location.origin+window.location.pathname==lockifyGlobals.linkUrl){var hash=document.location.hash.substring(1);var mm=hash.match(/([A-Za-z0-9-_]{43}).*/);if(mm){if(settings.url.indexOf(hash)!=-1||(typeof settings.data=='string'&&settings.data.indexOf(hash)!=-1)){xhr.abort();var cleanUrl=settings.url.replace(hash,'REMOVED');throw'Error: ajax request to '+cleanUrl+' contains decryption key. Request aborted.';return false;}}}
if(typeof(document.ajax_domain)!=='undefined'){if(settings.url.indexOf('http')!=0){settings.url=document.ajax_domain+settings.url;}}
settings.dataFilter=function(resultData,dataType){resultData=resultData.replace(/^while\(1\);/,'');return $.secureEvalJSON(JSON.stringify(resultData));};if(lockify.account.userInfo.get('csrf_token')&&!lockifyAjax.safeMethod(settings.type)&&lockifyAjax.sameOrigin(settings.url)){xhr.setRequestHeader("X-CSRFToken",lockify.account.userInfo.get('csrf_token'));}
xhr.setRequestHeader("X-LockifyClientType",lockifyGlobals.client_type);});$(document).ajaxSuccess(function(event,xhr,settings){if(xhr){var json=$.secureEvalJSON(settings.dataFilter(xhr.responseText,'json'));if(json&&json.ratelimit_blocked){rateLimitMessages(json||{});}}});if(typeof window.addEventListener!="undefined"){window.addEventListener('load',function(){new FastClick(document.body);},false);}
var hashReloadExceptions;$(document).ready(function(){$('.smallBriefLoading').spinnerFont();$('.briefLoading').spinnerFont();if(typeof InstanceBarView=="function"){instanceBarView=new InstanceBarView({'el':'#instance-flag','model':null});}
if(typeof ChromePromoBarView==="function"){new ChromePromoBarView({el:$('#extension_promo'),model:null});}
if(typeof ChromeExtView==="function"){new ChromeExtView({el:$('#chromeExtContent'),model:null});}
if(typeof EmailFeedbackView=="function"){emailFeedbackView=new EmailFeedbackView({'el':'#feedbackDialog','model':null});}
var utilityLinks=null;if(typeof UtilityLinksView=='function'){utilityLinks=new UtilityLinksView({el:$('.utilityLinks'),model:null});}
if(typeof UtilityPanelsView=='function'){new UtilityPanelsView({el:$('#expressUtilityPanels'),model:null,linksView:utilityLinks});}
if(typeof BrowsersView=="function"){browsersView=new BrowsersView({'el':'.browser-info #notaccordion','model':null});}
if(typeof CookiesView=="function"){cookiesView=new CookiesView({'el':'.cookie-info #notaccordion','model':null});}
if(typeof VersionInfoView=='function'){new VersionInfoView({el:$('#footer'),model:null});}
if(typeof ChromeClientInstallView=='function'){chromeClientInstallView=new ChromeClientInstallView({el:'.chromeClientInstall',model:null});}
if(typeof utilityDropdownView=='function'){new utilityDropdownView({el:$('#userDropdown'),model:null});}
if(typeof slideMenuView=='function'){new slideMenuView({el:$('#menuDropdown'),model:null});}
$(".sidebar").find(".sidebarPanel:first-child").addClass("first");$(".sidebar").find(".sidebarPanel:last-child").addClass("last");$(document).on("mouseover","input[type=checkbox]",function(){$(this).siblings('label').addClass('hover');if($(this).siblings('label').children().size()>0){$(this).siblings('label').children().addClass('hover');}}).on("mouseout","input[type=checkbox]",function(){$(this).siblings('label').removeClass('hover');if($(this).siblings('label').children().size()>0){$(this).siblings('label').children().removeClass('hover');}});$(document).on("mouseover","label",function(){if($(this).siblings().hasClass('checker')||$(this).siblings().hasClass('radio')){$(this).addClass('hover');$(this).siblings('.checker, .radio').addClass('hover');}
if($(this).children().size()>0){$(this).children().addClass('hover');}}).on("mouseout","label",function(){if($(this).siblings().hasClass('checker')||$(this).siblings().hasClass('radio')){$(this).removeClass('hover');$(this).siblings('.checker, .radio').removeClass('hover').removeClass('focus');}
if($(this).children().size()>0){$(this).children().removeClass('hover');}});$(document).on("focus",".prependInput",function(){$(this).prev(".prependItem").addClass('focus');}).on("blur",".prependInput",function(){$(this).prev(".prependItem").removeClass('focus');});$(document).on("mouseover",".prependInput",function(){$(this).next('input').addClass('hover');}).on("mouseout",".prependInput",function(){$(this).next('input').removeClass('hover');});$(".prependItem").click(function(){$(this).next('input').focus();});$('#lockoutDialog .showTrigger').click(function(){$(this).children('.icomoon-icon').toggleClass('icon-plus').toggleClass('icon-minus');$(this).next('span').toggle();});$(document).on('focus','.toggleMaskInput',function(){$(this).parent().addClass('focus');}).on('blur','.toggleMaskInput',function(){$(this).parent().removeClass('focus');});if(typeof jQuery.fn.noticeBox=='function'){$('.notice').noticeBox();}
$(document).ajaxError(function(event,xhr,ajaxOptions,jsException){var ajaxOptionsClean=_.clone(ajaxOptions);ajaxOptionsClean.data=null;try{switch(xhr.status){case 401:case 403:case 404:case 500:Exception.handle("XHR: \n"+JSON.stringify(xhr)+"\najaxOptions: \n"+JSON.stringify(ajaxOptionsClean),event.target.URL);return;case 500:return;}}
catch(e){}
if(typeof jsException!="undefined"){return;}});var anchor=window.location.hash;hashReloadExceptions=["#","#learningmode","#encrypt","#decrypt","#reset_password","#resend_activation_link","#general","#defaults","#lists","#Accountsettings","#Lockificationdefaults","#Handlingauthenticationinformation","#LockifyMe","#Inviteafriend","#API","#Alerts","#Mailinglist","#multiple"];var checkForAnchorChange=function(){if(anchor!=window.location.hash&&anchor.length&&$.inArray(anchor,hashReloadExceptions)==-1){window.location.reload();anchor=window.location.hash;}};var thisUrl=window.location.protocol+"//"+window.location.hostname+(window.location.port.length?":"+window.location.port:"")+window.location.pathname;if(typeof(lockifyGlobals.linkUrl)!="undefined"&&lockifyGlobals.linkUrl==thisUrl){setInterval(checkForAnchorChange,1000);}
if(typeof(BOOKMARKLET_ENCRYPT_URL)!=='undefined'){$('a.bookmarklet').each(function(){var baseURL=BOOKMARKLET_ENCRYPT_URL||(window.location.protocol+'//'+window.location.host+'/');this.href=this.href.replace('_BOOKMARKLET_ENCRYPT_URL_',baseURL);});}
CLOSE_ANSWER_REGEX=/[^0-9a-zA-Z]|\bthe\b|\ba\b|\ban\b/g;CANONICAL_STRONG_PASSWORD="abcABC123!@#";$(document).on('click',".dialogClose",{},function(){$(this).parent().parent().parent('.ui-dialog-content').dialog('close');});$(document).on('click',".cancelLink",{},function(){$(this).trigger('deanimate');$(this).parent().parent().parent('.ui-dialog-content').dialog('close');});(function(){var styleCurrentNavbarItem=function(){if(($(this).attr("href").replace(/\/$/,"")==window.location.pathname.replace(/\/$/,"")||($(this).text()=="Home"&&window.location.pathname.match(/\/index[\/|\.html]/)))&&!($(this).text()=="Home"&&window.location.hash.length>1))
{var span=$("<span>");span.addClass("current");span.html($(this).html());span.data("href",$(this).attr("href"));if($(this).hasClass("last")){span.addClass("last");}
if($(this).hasClass("first")){span.addClass("first");}
$(this).remove();return false;}};})();(function(){$(".icon-help.inline").on('click',function(){var helpElem=$(this).data('contentSel');if($(this).hasClass('open')){$(this).removeClass('open');$(helpElem).slideUp();}else{$(this).addClass('open');$(helpElem).slideDown();}});})();if(typeof DiagramDialogView=='function'){new DiagramDialogView({el:$('#diagramDialog'),model:null});}
$(".openInviteDialog").click(function(){$("#inviteDialog").dialog(dialogOptions);});$(".openVersionInfo").click(function(){$('#versionInfoDialog').dialog(dialogOptions);});$(".openFeedbackDialog").click(function(){$('#feedbackDialog').dialog(dialogOptions);});lockifyUtils.setupQtips('#expireLimitsRefresh');var handleRefreshActive=function(){$("#valuesContainer").addClass('hover').removeClass('refresh').removeClass('refreshDelay');$("#expireLimitsRefresh").addClass('hover');};var handleRefreshInactive=function(){$("#valuesContainer").removeClass('hover');$("#expireLimitsRefresh").removeClass('hover');};$(document).on("mouseover","#expireLimitsRefresh",function(){handleRefreshActive();}).on("mouseout","#expireLimitsRefresh",function(){handleRefreshInactive();});$("#expireLimitsRefresh").focus(function(){handleRefreshActive();}).blur(function(){handleRefreshInactive();});$('.expressInvite').click(function(){if($('body').is('.express, .login')){window.location.hash='#reserve_spot';}
$("#betaListSubscribeDialog").dialog(dialogOptions);});$('.subscribeClose').click(function(){$('#betaListSubscribeDialog').dialog('close');});$('.openExpressLearn').click(function(){$('#expressBenefitsDialog').dialog(dialogOptions);});$(".toggleTrigger").on('click',function(){lockifyUtils.handleToggle(this);});$('.toggleIcon').click(function(){$(this).parent().parent().siblings('.toggleTrigger').click();});if(typeof InfoBannerView=="function"){var cookieName="hidepreviewalert";if($.cookie(cookieName)!=1){new InfoBannerView({el:$('#previewBand'),cookieName:cookieName});}else{$('#previewBand').remove();$('#bottom_fade').css('bottom','0');}
new InfoBannerView({el:$('#cprngWarningBand'),cookieName:cookieName});}else{$('#previewBand, #cprngWarningBand').remove();$('#bottom_fade').css('bottom','0');}
$(".dialogFooter:empty").hide().prev(".dialogContent").addClass("footerless");if($.browser.chrome&&parseInt($.browser.version,10)<20){lockifyUtils.refreshBackgrounds("#showConsole");}
$(document).bind('formBoundToUserPrefs',lockifyUtils.hideLoadingCover);});$(document).bind('userAuthComplete',function(){if(!$('#loadingCover').length){if(Modernizr.cssanimations){$('#page').addClass('fadeIn');}else{$('#page').addClass('showIE');}}});