/*
 * Lockify Index
 * Copyright 2010 Lockify Inc. All Rights Reserved.
 * License:
 * Contains functions to validate the message and files
 * entered and auth options selected and encrypts the data and
 * generates the output link
 */
var gEncryptionIsInited=false;var expirationLimitsView,authMethodView,moreOptionsView,howdyDoBarView;var submitAndResetView;function handleOutput(json){if(typeof window.scroll=='function'){window.scroll(0,0);}
if(typeof LinkDisplayView=='function'){new LinkDisplayView({el:$('#linkDisplay'),model:lockify.index.entry});}
if(typeof ShareLinkView=='function'){new ShareLinkView({el:$('#sharingOptions'),model:lockify.index.entry});}
if(typeof QrcodeEncryptView=='function'){new QrcodeEncryptView({el:$("#outputExtras"),model:lockify.index.entry});}
if(typeof QrPrintDialogView=='function'){new QrPrintDialogView({el:$("#qrPrintDialog"),model:null});}
if(typeof OutputExpirationLimitsView=='function'){new OutputExpirationLimitsView({el:$('#remainingViewsContainer'),model:lockify.index.entry,remainingViews:json.remaining_views,remainingTime:json.remaining_time});}
if(typeof OutputMessageView=='function'){new OutputMessageView({el:$('#outputMessageToggle'),model:lockify.index.entry,remainingViews:json.remaining_views,remainingTime:json.remaining_time});}
if(typeof NicknameView=='function'){new NicknameView({el:$('#nicknameContainer2'),model:lockify.index.entry});}
if(typeof outputMetaView=='function'){new outputMetaView({el:$('#outputMeta'),model:lockify.index.entry});}
$(document).trigger('linkCreated',[lockify.index.entry.get('dataHash'),lockify.index.entry.get('cryptoAssets'),lockify.index.entry.get('outUrl').length]);if($("#enableEvents").prop("checked")){$('#divAdminInfo').show();}
$('#publicId').text(json.public_id);var trackLink=$(".newLinkTrack");trackLink.attr('href',trackLink.attr('href')+'?hl='+json.public_id);if($('#divBetween').is(':visible')){$('#divBetween').removeClass('fadeIn').hide();}
if($('#encryptHowdyContent').is(':visible')){$('#encryptHowdyContent').hide();}
if($('#encryptLoading').is(':visible')){$('#encryptLoading').hide();}
$('.lastText').show();$('.defaultText').hide();$('#outputTips').show();$(".doneLinkList li:nth-child(even)").addClass("even");$('#output').focus();$(document).trigger('newLinkUiPopulated');}
function _encryptionCompleteCallback(){if($('html').data('debug')&&lockify.index.entry.get('testError')=='javascript'){throw new Error("This is a test javascript error that can be safely ignored.");}
var showProgBars=lockify.index.entry.totalDataLength()/1024>=lockifyIndexGlobals.uploadProgressMinKb;if(showProgBars){$('#encryptLoading').hide();var nullCount=0;var checkProgress=function(progressId){lockifyAjax.ajaxJSONSafe(lockifyIndexGlobals.savePath+"/progress",null,function(json){if(json===null){nullCount++;if(nullCount>5){clearInterval(upProgInt);}
return;}
var val=json.uploaded/json.length;if(val>=1.0){clearInterval(upProgInt);}
if(lockify.index.entry.totalDataLength()/1024>=lockifyIndexGlobals.uploadProgressMinKb){$(document).trigger('up-progress',[val,true]);}},function(json){clearInterval(upProgInt);},null,{},{"X-Progress-ID":lockify.index.entry.get('cryptoAssets').adminCredHash});};var upProgInt=setInterval(checkProgress,2000);}
lockifyAjax.ajaxJSONSafe(lockifyIndexGlobals.savePath,lockify.index.entry.createDataString(),function(json){lockify.index.entry.set("publicId",json['public_id']);lockify.index.entry.id=json['public_id'];if(json&&json.success){if(lockify.index.entry.totalDataLength()/1024>=lockifyIndexGlobals.uploadProgressMinKb){$(document).trigger('up-progress',[1,true,function(){handleOutput(json);}]);}else{handleOutput(json);}}else{if(json.ratelimit_blocked){$('#divInput').show();var unblockSave=function(){submitAndResetView.enableSubmitButton();$(document).unbind('ratelimitLockoutEnded',unblockSave);};$(document).bind('ratelimitLockoutEnded',unblockSave);}else if(json.permissionDenied){$('#outputContainer, #linkDetailsContainer, #thirdScreen .sharingOptions').hide();$('#outputContainerError').removeClass('defaultHide').find('.content').text("We could not save your Lockify Link because you are no longer signed in to Lockify.");}else{alert(json.error);}}},function(){submitAndResetView.disableSubmitButton();},(lockify.index.entry.get('testError')=="timeout"?100:null),"multipart/form-data; boundary=---------------------------1504702169761927311267328916",{"X-Progress-ID":lockify.index.entry.get('cryptoAssets').adminCredHash});return false;}
function handleSubmission(e){if(e&&typeof(e.preventDefault)!=='undefined'){e.preventDefault();}
submitAndResetView.disableSubmitButton();var isValid=lockify.index.validateSubmission(e);if(!isValid){submitAndResetView.enableSubmitButton();return false;}
$(".newlink").children("a").addClass("current");if($('#encryptContent').is(':visible')){$('#encryptContent').hide();}
return lockify.index.performEncryption();}
function encryptPageOnReady(){$("#divInput").show();if(lockifyUtils.getUrlParam('firstlogin')==1){$('#welcomeDialog').dialog(dialogOptions);}
if(lockifyUtils.getUrlParam('cprngwarn')==1){$('#cprngWarningBand').removeClass('defaultHide');}
if(gEncryptionIsInited){return;}
lockify.index.entry=new EntryModel({baseUrl:lockifyGlobals.linkUrl||(window.location.protocol+'//'+window.location.host+'/'),testError:lockifyUtils.getUrlParam('testError'),allowManualExpiration:lockifyGlobals.DEFAULT_MANUAL_EXPIRATION_BY_RECIPIENT});gEncryptionIsInited=true;new PlainInputView({el:$('#dataContainer').eq(0),model:lockify.index.entry});if(typeof HowdyDoBarView=='function'){howdyDoBarView=new HowdyDoBarView({el:$('#howdy'),model:new UrlPrefModel({name:'showHelloBar',value:null})});}
if(typeof ExpirationLimitsView=='function'){expirationLimitsView=new ExpirationLimitsView({el:$('#expireDiv').eq(0),model:lockify.index.entry});}
if(typeof NicknameView=='function'){new NicknameView({el:$('#nicknameContainer'),model:lockify.index.entry});}
if(typeof AuthMethodView=='function'){authMethodView=new AuthMethodView({el:$('#authContainer_outer').eq(0).parent(),model:lockify.index.entry});}
if(typeof AuthPasswordView=='function'){new AuthPasswordView({el:$('#authOptionPass_panel').eq(0),model:lockify.index.entry});}
if(typeof AuthSecQuesView=='function'){new AuthSecQuesView({el:$('#authOptionQA_panel').eq(0),model:lockify.index.entry,MAX_SECURITY_ANSWERS:lockifyIndexGlobals.maxSecurityAnswers,MIN_CHARS_ENABLE_CLOSE:lockifyIndexGlobals.minCharsEnableClose,CLOSE_ANSWER_REGEX:CLOSE_ANSWER_REGEX});}
if(typeof AuthGoogleView=='function'){new AuthGoogleView({el:$('#authOptionGoogle_panel').eq(0),model:lockify.index.entry,MAX_GMAIL_IDS:lockifyIndexGlobals.maxGmailIds});}
if(typeof AuthOpenIdView=='function'){new AuthOpenIdView({el:$('#authOptionOpenId_panel').eq(0),model:lockify.index.entry,MAX_OPENID_IDS:lockifyIndexGlobals.maxOpenIdIds});}
if(typeof AuthTwitterView=='function'){new AuthTwitterView({el:$('#authOptionTwitter_panel').eq(0),model:lockify.index.entry,MAX_TWITTER_IDS:lockifyIndexGlobals.maxTwitterIds});}
if(typeof AuthPhoneView=='function'){new AuthPhoneView({el:$('#authOptionPhone_panel').eq(0),model:lockify.index.entry,MAX_PHONE_NUMBERS:lockifyIndexGlobals.otpMaxPhoneNumbers});}
if(typeof AuthNativeView=='function'){new AuthNativeView({el:$('#authOptionNative_panel').eq(0),model:lockify.index.entry,MAX_NATIVE_IDS:lockifyIndexGlobals.maxNativeIds});}
if(typeof AuthEmailView=='function'){new AuthEmailView({el:$('#authOptionEmail_panel').eq(0),model:lockify.index.entry,MAX_EMAIL_ADDRESSES:lockifyIndexGlobals.maxEmailAddresses});}
if(typeof BitStrengthView=='function'){new BitStrengthView({el:$('#bitStrengthContainer').eq(0),model:lockify.index.entry});}
if(typeof FlashCopyOptionView=='function'){new FlashCopyOptionView({el:$('#flashCopyOption'),model:null});}
if(typeof ShortLinkOptionView=='function'){new ShortLinkOptionView({el:$('#shortLinkOption'),model:lockify.index.entry});}
if(typeof CopyPrintExpireView=='function'){new CopyPrintExpireView({el:$('#viewerOptionsContainer'),model:lockify.index.entry,saveOnChange:false});}
if(typeof SpecifyDecryptClientView=='function'){new SpecifyDecryptClientView({el:$('#specifyClientLabel'),model:lockify.index.entry,saveOnChange:false});}
if(typeof NotificationsView=='function'){new NotificationsView({el:$('#notifyContainer'),model:lockify.index.entry,saveOnChange:false});}
if(typeof CryptoAssetHandlingView=='function'){new CryptoAssetHandlingView({el:$('#assetForLinkContainer'),model:lockify.index.entry});}
submitAndResetView=new SubmitAndResetView({el:$('.submitDiv'),model:lockify.index.entry});$('#generateLink').click(function(e){lockifyUtils.setOnBeforeUnloadMsg('Any information entered so far will be lost if you navigate away from or reload this page.');var isValid=lockify.index.validateSubmission(e);if(isValid){return lockify.index.performMessageEncryption();}
$(this).trigger('deanimate');return false;});$("#outputTips span").click(function(){$("#linkTipsDialog").dialog(dialogOptions);});$("#authTips span").click(function(){$("#authTipsDialog").dialog(dialogOptions);});$("#addFileAccount .link").click(function(){$(".expressRegister").click();});var elem=$('.triggerInfoSlide');elem.click(function(){var slideElem=$('#infoSlideCover');if(slideElem.is(':hidden')){slideElem.removeClass('defaultHide');slideElem.children('div').slideToggle(function(){slideElem.addClass('open');});}else{slideElem.removeClass('open');slideElem.children('div').slideToggle(function(){slideElem.addClass('defaultHide');});}
elem.toggleClass('open');elem.children('span').toggleClass('defaultHide');});$(document).trigger('encryptPageReady');$('#advUi input:radio[name=assetForLink]:checked').click();setTimeout(function(){$(document).trigger('encryptPageActionsInitialized');},2000);}
$(document).ready(encryptPageOnReady);if(typeof sjclE.random.RandomInit=="function"){sjclE.random.RandomInit();Random.add_entropy(new Date().getTime(),0,'load_start_time');lockifyEntropy.bindEntropyEvents();}
function handleProgress(event,progressVal,animate,callback){if(typeof animate==='undefined'){animate=false;}
var p=0;if(event.type=='enc-progress'){p=Math.floor((progressVal*100)/2);}
if(event.type=='up-progress'){p=Math.floor((progressVal*100)/2+50);}
if(!animate){$('#encryptMeter').progressbar("value",p);if(typeof callback=="function"){setTimeout(callback,500);}}else{var anim;if(anim){clearInterval(anim);}
anim=setInterval(function(){var val=$('#encryptMeter').progressbar("value");if(p>parseInt(val,10)){$('#encryptMeter').progressbar("value",val+1);}else{clearInterval(anim);if(typeof callback=="function"){setTimeout(callback,500);}}},50);}}
function encryptFileDialog(){if($('#collectingEntropy').is(':visible')){$('#collectingEntropy').hide();$('#entropyHelpContainer').hide();}
if(lockify.index.entry.totalDataLength()/1024>=lockifyIndexGlobals.uploadProgressMinKb){$('#encryptLoading').hide();$('#encryptionProgress').show();}
var encryptComplete=function(event){$('#encryptionProgress .status').text('Uploading encrypted data.');$('#encryptMeter').progressbar("value",50);if(lockify.index.entry.totalDataLength()/1024>=lockifyIndexGlobals.uploadProgressMinKb){handleProgress(event,0.5,true);}
$(document).bind('up-progress',handleProgress);};var encryptFileComplete=function(event){$(document).unbind('enc-progress');if(lockify.index.entry.totalDataLength()/1024>=lockifyIndexGlobals.uploadProgressMinKb){handleProgress(event,0.5,true);}
$(document).bind('up-progress',handleProgress);};$(document).bind('enc-end',encryptFileComplete);$(document).bind('enc-auth',encryptComplete);}
lockify.index={collectKeyEntropy:{},entry:{},hideAnonElemsAfterSignin:function(){$('.nonauthenticatedUserOnly').hide();$('.authenticatedUserOnly').show();$('.makeNewAnchor').attr('href',$('.makeNewAnchor').data('authpath'));if(typeof EarlyExpireView=='function'){$('#expireEarlyOption').insertAfter('#btnAdminDelete');this.earlyExpire=new EarlyExpireView({el:$('#expireEarlyOption'),model:lockify.index.entry,saveOnChange:true,doDefaultCheck:true});}
$('body').removeClass('guestUser express futurehomepage').addClass('e');$("#expressUtilityPanels").bind('dialogclose',function(event){$("#userSignedIn").dialog($.extend({},dialogOptions,{modal:false,dialogClass:"blip",open:function(event,ui){setTimeout(function(){try{$("#userSignedIn").dialog('close');}catch(x){}
$("#expressUtilityPanels").unbind('dialogclose');},2500);}}));});$('#commonLinkSettings').insertBefore('#remainingViewsContainer');var userPrefs=document.lockifyUserEntryDefaults.attributes;if(typeof userPrefs.enable_message_copying=='boolean'){$('#easyCopy').prop('checked',!userPrefs.enable_message_copying?"checked":null);}
if(typeof userPrefs.enable_message_printing=='boolean'){$('#easyPrint').prop('checked',!userPrefs.enable_message_printing?"checked":null);}
if(typeof userPrefs.allowManualExpiration=='boolean'){$('#allowExpire').prop('checked',userPrefs.allowManualExpiration?"checked":null);}
if(typeof userPrefs.receiveNotifications=='boolean'){$('#notify').prop('checked',!userPrefs.receiveNotifications?"checked":null);}
$(document).trigger('migrateToSignedOn');},performMessageEncryption:function(){$('#encryptMeter').progressbar({value:0});var callback=null;if(!lockifyCryptoUtils.nativeCryptoAvailable()&&!Random.is_ready()){Random.addEventListener('seeded',function(){lockify.index.entry.encrypt(callback,"encryptMessage");$('#resetEntropy').hide();});}else{lockify.index.entry.encrypt(callback,"encryptMessage");}},validateSubmission:function(e){$(document).trigger('clearErrors');var isValid=lockify.index.entry.validateForEncryption();if(!isValid&&$("#stepOne .error").length){$('#data').focus().blur();$(document).trigger('clearErrors');isValid=lockify.index.entry.validateForEncryption();}
if(!isValid){if(e.stopImmediatePropagation){e.stopImmediatePropagation();}
submitAndResetView.enableSubmitButton();}
return isValid;},newLinkUiIsPopulated:false,performEncryption:function(){var self=this;var _performEncryption=function(){var isBrowserWithFlashBug=($.browser.webkit&&!lockifyUtils.isHtml5Enabled())||($.browser.mozilla&&parseInt($.browser.version,10)<=12)||($.browser.msie&&parseInt($.browser.version,10)<=10)||$.browser.safari;var _showProgress=function(){$('#encryptLoading').hide();$('#encryptionProgress').show();$('#divBetween').show().addClass('fadeIn');$(document).bind('newLinkUiPopulated',_showSecondScreen);};var _showLoading=function(){$('#encryptLoading').show();$('#encryptionProgress').hide();$('#divBetween').show().addClass('fadeIn');$(document).bind('newLinkUiPopulated',_showSecondScreen);};var _hideBetween=function(){$('#divBetween').removeClass('fadeIn').hide();};var _fadeInBar=function(){lockifyUtils.cssFadeIn('.output-sec-bar');$("#output").focus();$('.makeNewAnchor').attr('href',window.location.pathname);};var _showSecondScreen=function(){_hideBetween();if($('body').hasClass('guestUser')){}else{$('#commonLinkSettings').insertBefore('#remainingViewsContainer');}
var animElem=$('#divOutput');if(Modernizr.cssanimations){animElem.show().removeClass('defaultHide').addClass('slideInRight');animElem.one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',_fadeInBar);}else{animElem.show().removeClass('defaultHide');_fadeInBar();}};var _hideFirstScreen=function(){$('#divInput').hide();$('#expireDiv').hide();$(window).resize();if(lockify.index.entry.totalDataLength()/1024>=lockifyIndexGlobals.uploadProgressMinKb){_showProgress();$(document).bind('enc-progress',handleProgress);}else{if(self.newLinkUiIsPopulated){_showSecondScreen();}else{_showLoading();}}};var _slideFirstScreen=function(){if(Modernizr.cssanimations){if($('body').hasClass('popup')){$('#expireDiv').addClass('slideOutLeft');}
var animElem=$('#divInput');animElem.addClass('slideOutLeft');animElem.one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',_hideFirstScreen);}else{_hideFirstScreen();}};var _showAfterCollapse=function(){if(!isBrowserWithFlashBug){_slideFirstScreen();}else if(lockifyUtils.isFlashInstalled()){var curFileCount=typeof fileListView!="undefined"?fileListView.fileCount():0;if(curFileCount>0){var newPb=$('<div id="newPb"></div>');newPb.insertBefore('#generateLink');newPb.progressbar({value:0});var newPbText=$('<div id="newPbText">Encrypting your private info.</div>');newPbText.insertAfter('#generateLink');$(document).bind('enc-progress',function(event,progressVal){$('#newPb').progressbar("value",Math.floor(progressVal*100));});$(document).bind('newLinkUiPopulated',function(event){if(Modernizr.cssanimations){var animElem=$('#divInput');animElem.addClass('slideOutLeft');animElem.one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend',function(){$('#divInput').hide();_showSecondScreen();});}else{_showSecondScreen();}});}else{_slideFirstScreen();}}else{_slideFirstScreen();}};var payloadDescription=lockify.index.entry.getPayloadDescription();var payloadItemCount=lockify.index.entry.getPayloadItemCount();$('.payloadDescription').text(payloadDescription);$('.payloadDescriptionFull').text(payloadDescription+(payloadItemCount==1?" was":" were"));_showAfterCollapse();var cryptoAssets=lockify.index.entry.get('cryptoAssets');if(typeof cryptoAssets=='undefined'||cryptoAssets===null){$(document).bind('enc-end',function(){encryptFileDialog();$(document).unbind('enc-end');lockify.index.entry.encrypt(_encryptionCompleteCallback,"encryptAuth");});return false;}else{encryptFileDialog();$(document).unbind('enc-end');lockify.index.entry.encrypt(_encryptionCompleteCallback,"encryptAuth");}
lockifyUtils.setOnBeforeUnloadMsg("If you haven't already, copy your link before leaving.");};$(document).bind('newLinkUiPopulated',function(){self.newLinkUiIsPopulated=true;$('#expireEarlyOption').insertAfter('#btnAdminDelete');});if(!lockifyCryptoUtils.nativeCryptoAvailable()&&!Random.is_ready()){$('#divBetween').show().addClass('fadeIn');$("#collectingEntropy").fadeIn(1000);$("#entropyMeterContainer").hide().show();$(document).bind('enc-end',_performEncryption);}else{_performEncryption();}}};