lockify.gateway={gOpenIDCallbackQuerystring:null,gOpenIDState:null,authGmailDecryptView:{},authTwitterDecryptView:{},fileDecryptView:{},salt:{},keyBytes:{},key:{},crypt_str:{},linkAcceptsCloseAnswers:{},dataHash:{},supportsDownloadAttribute:{},gFlashFileDownloads:[],showDownloadProgress:false,decryptButtonInterval:null,decryptButtonCycle:0,baseDecryptOutputView:{},fillWithText:function($container,text){$container.empty();var lines=text.split("\n");for(var i=0;i<lines.length;i++){if(lines[i].length){$('<div>').text(lines[i]).appendTo($container);}else{$('<div>').html("<br/>").appendTo($container);}}},decryptPageOnReady:function(){var authSecQuesDecryptView,authPassDecryptView,authEmailDecryptView,authPasswordDecryptView,authNativeDecryptView,confirmTrustBtn,integratedEmailDecryptView;lockify.gateway.supportsDownloadAttribute='download'in $('<a>').get(0);$('#divGateway form').eq(0).bind('submit',function(){return false;});$('#divInput').remove();$('#pwordPanel').remove();$(".doneLinkList li:nth-child(even)").addClass("even");var mm=window.location.hash.match(/#([A-Za-z0-9-_]{22,43}).*/);try{lockify.gateway.crypt_str=mm[1];}catch(x){var errorSpecific;if(x.name=="TypeError"){errorSpecific="This is not a valid link.";}else{errorSpecific=x.message;}
$("#unknownDiv").show();$('.briefLoading').hide();$('#unknownDiv .meta').text(errorSpecific);return;}
if($('#pasteLinkInput').length>0){lockify.gateway.crypt_str=$('#pasteLinkInput').val();}
lockify.gateway.dataHash=lockifyCryptoUtils.hash_sha256_b64u(lockify.gateway.crypt_str);var autoDecrypt=false;$(document).bind('userAuthComplete',function(){lockifyAjax.ajaxJSONSafe("/get/auth_info/","dh="+encodeURIComponent(lockify.gateway.dataHash),function(json){if(json.cipherTextLength/1024>=lockifyIndexGlobals.uploadProgressMinKb){lockify.gateway.showDownloadProgress=true;}
if(!json){alert('Sorry, the page could not be loaded. Please try again later.');return;}
switch(json.status){case'deleted':lockifyUtils.showDeletedMessage(json);break;case'locked':$("#onHoldDiv").show();$("#validDiv").hide();$("#onHoldDiv").find("#deletedItem").text(json.serverStoredAsset=="ciphertext"?"encrypted data":"decryption key");break;case'unknown':$("#unknownDiv").show();$('.briefLoading').hide();break;case'normal':$("#validDiv").show();if(json.clientTypes&&json.clientTypes.length&&json.clientTypes.indexOf(lockifyGlobals.client_type.toUpperCase())==-1){lockify.gateway.handleWrongClientType(json.clientTypes);return;}
if(json.isLinkOwner&&typeof OwnerView=='function'&&$('#confirmTrust .isOwnerMsg').length){new OwnerView({el:$('#confirmTrust .isOwnerMsg'),model:null});}
lockify.gateway.salt=json.salt;lockify.gateway.linkAcceptsCloseAnswers=json.LINK_ACCEPTS_CLOSE_ANSWERS;if(typeof swfobject!='undefined'&&!($.browser.webkit&&lockifyUtils.isHtml5Enabled())){if(json.localFileWriterRequired){if(!swfobject.hasFlashPlayerVersion('0.0.1')){$('#noFlashPluginMsg').removeClass('defaultHide');$('.continueLink').remove();$('#friendlyTip').addClass('top');return;}else if(!swfobject.hasFlashPlayerVersion(lockifyIndexGlobals.minFlashWriterVersion)){$('#wrongFlashPluginVersionMsg').removeClass('defaultHide');return;}}}else{if(lockifyUtils.isMobile&&json.localFileWriterRequired){$('#noFlashPluginMsg').removeClass('defaultHide');$('.continueLink').remove();$('#friendlyTip').addClass('top');return;}}
if(typeof QrcodeDecryptView=='function'){new QrcodeDecryptView({el:$("#decryptQrcode"),model:null});}
var authInfoKey=lockifyCryptoUtils.URLBase64ToBase64(lockify.gateway.crypt_str);var buttonElem=$('#confirmTrustBtn');buttonElem.children('.btnText').html(buttonElem.data('methodtext'));switch(json.auth_type){case'security_question':var json_text=json.security_question_text||lockify.sjclBridge.decrypt.decrypts(json.security_question_text_aes256||'',authInfoKey);authSecQuesDecryptView=new AuthSecQuesDecryptView({el:$('#authUi_secQues'),question_text:json_text});break;case'password':authPassDecryptView=new AuthPassDecryptView({el:$('#authUi_password')});break;case'openid':lockify.gateway.authGmailDecryptView=new AuthGmailDecryptView({el:$('#authUi_openid'),json:json,authkey:authInfoKey});authcomplete=lockify.gateway.authGmailDecryptView;break;case'twitter':lockify.gateway.authTwitterDecryptView=new AuthTwitterDecryptView({el:$('#authUi_twitter'),datahash:lockify.gateway.dataHash,json:json,authkey:authInfoKey});authcomplete=lockify.gateway.authTwitterDecryptView;break;case'native':authNativeDecryptView=new AuthNativeDecryptView({el:$('#authUi_lockifyUser'),json:json,authkey:authInfoKey});break;case'phone':if(typeof authPhoneDecryptView!='undefined'){authPhoneDecryptView.undelegateEvents();}
authPhoneDecryptView=new AuthPhoneDecryptView({el:$('#authUi_phoneNumber'),json:json,auth_infoKey:authInfoKey});break;case'intEmail':if(typeof authNativeDecryptView!='undefined'){authNativeDecryptView.undelegateEvents();}
if(typeof integratedEmailDecryptView!='undefined'){integratedEmailDecryptView.undelegateEvents();}
if(json.is_native_user===true){authNativeDecryptView=new AuthNativeDecryptView({el:$('#authUi_lockifyUser'),json:json,authkey:authInfoKey});}else{integratedEmailDecryptView=new IntegratedEmailAuthDecryptView({el:$('#authUi_integratedemail'),json:json,authInfoKey:authInfoKey,model:new EntryEmailStatusModel(),checkUserIdWithServer:json.checkUserIdWithServer});}
break;case'email':if(typeof AuthEmailDecryptView!='undefined'){lockify.gateway.authEmailDecryptView=new AuthEmailDecryptView({el:$('#authUi_email'),json:json,auth_infoKey:authInfoKey,showOnStart:true});}
break;default:autoDecrypt=true;buttonElem.children('.btnText').html(buttonElem.data('decrypttext'));break;}
$("#getSecret").removeAttr("disabled");if(typeof json.browser_perf_warning!='undefined'){$('#notYours').bind('opened',function(){$("#browserPerfDialog div.message").text(json.browser_perf_warning);$("#browserPerfDialog").dialog($.extend({},dialogOptions,{height:'auto',closeOnEscape:false}));});}
break;}});});$('#confirmTrustBtn').one("click",function(){confirmTrustBtn=new ConfirmTrustButtonView({el:$('#confirmTrust'),autoDecrypt:autoDecrypt,twitterView:lockify.gateway.authTwitterDecryptView,gmailView:lockify.gateway.authGmailDecryptView,nativeView:authNativeDecryptView});});$(".abortLink").click(function(){$("#checkpointAbortDialog").dialog(dialogOptions);});},handleWrongClientType:function(allowedTypes){$('.continueLink').hide();$('.currentUrl').text(lockifyGlobals.linkUrl+"#"+lockify.gateway.crypt_str);if(lockifyUtils.isMobile||navigator.userAgent.match('Chrome')==null){$('#clientNotAllowedMsg-getChrome').removeClass('defaultHide');}else{if($('.extDetected').data('detected')){$('#clientNotAllowedMsg-extDetected').removeClass('defaultHide');}else{$('#clientNotAllowedMsg-extNotDetected').removeClass('defaultHide');}}
$('#clientNotAllowedMsg').removeClass('defaultHide');$(".currentUrl").animate({opacity:1.0},100,"linear",function(){try{if(document.createRange){var rangeToSelect=document.createRange();rangeToSelect.selectNode(this);var curSelect=window.getSelection();curSelect.removeAllRanges();curSelect.addRange(rangeToSelect);}
return false;}catch(x){return false;}});}};var authcomplete;if(window.location.hash.length>1&&window.location.hash.substr(0,8)!='#!input!'){$(document).ready(lockify.gateway.decryptPageOnReady);}
function configAbuseForm(){$('#btnReportAbuse').waitButton();$('#btnReportAbuse').click(function(){lockifyAjax.ajaxJSONSafeForm('/reportabuse',$('#abuseForm'),function(json){msgDiv=$('<div>');msgDiv.text(json.message);$('#abuseFeedback').val('');$('#abuseForm').hide().after(msgDiv);},null,null);});}
$(document).ready(function(){lockify.index.baseDecryptOutputView=new BaseDecryptOutputView({});if(typeof InviteRequest=='function'){new InviteRequest({el:$('div.betaListContainer'),model:null});}
$("#getSecret").waitButton();$("#getSecret").click(function(){lockify.index.baseDecryptOutputView.trigger('getSecretHandler',$(this));});$(".currentUrl").click(function(){$(this).animate({opacity:1.0},100,"linear",function(){if(document.createRange){var rangeToSelect=document.createRange();rangeToSelect.selectNode(this);var curSelect=window.getSelection();curSelect.removeAllRanges();curSelect.addRange(rangeToSelect);}
return false;});})
$(document).on("mouseover",".fileLinkCell",function(){$(this).siblings().addClass('hover');}).on("mouseout",".fileLinkCell",function(){$(this).siblings().removeClass('hover');});$(document).bind('userAuthComplete',function(e,is_authenticated){$(document).trigger('formBoundToUserPrefs');});});function authBegin(popup){$('#getSecret').prop('disabled',true).addClass('disabled');}
var tooManyRedirectsTimeout=null;function authComplete(querystring){authcomplete.trigger('authComplete',querystring);}