var AuthMethodView=Backbone.View.extend({defaults:{authSelect:null,defaultSlideDuration:1000,slideDuration:null},events:{"change #authOption":"handleAuthChange","mouseenter #authOption_select li":"handleSelectEnter","mouseleave #authOption_select li":"handleSelectLeave","click #authOption_select li":"handleSelectClick","mouseenter #authOption":"handleSelectIconEnter","mouseleave #authOption":"handleSelectIconLeave","focus #authOption":"handleSelectIconFocus","blur #authOption":"handleSelectIconBlur","click #cancelAuth":"handleCancelAuth"},initialize:function(){this.slideDuration=this.defaultSlideDuration;this.authSelect=$("#authOption").imageDropdown({'selectList':$("#authOption_select"),'initialIndex':0,'initialValue':'none','showSelectedItemInList':true,'highlightClass':'li-hover'});_.bindAll(this,['reset']);$(document).bind('formReset',this.reset);this.model.bind("authErrorOnly",this.handleAuthErrorOnly);_.bindAll(this,['handleCancelAuth']);$('#newAuthMethod').click(this.handleAuthChange);$('#listNoneItem').hide();},handleAuthChange:function(event,selectedIndex){if(!this.authSelect){return;}
var panelToShow=null;var panelVisible=$('.authOptionPanel:visible').length>0;var postShowCallback=null;this.model.set({authMethod:this.authSelect.val(),authService:null});$('.authOptionPanel').find('.tooltip-inline-content').hide();$('.authOptionPanel').find('.icon-help').removeClass('open');switch(this.model.get('authMethod')){case"none":if(panelVisible){if(this.authSelect){this.authSelect.disableKeys();}
$('.authOptionPanel:visible').slideUp(this.slideDuration,function(){this.slideDuration=this.defaultSlideDuration;if(authSelect){authSelect.enableKeys();}});}
if($('#publicAuthText').length){$('#publicAuthText').show();}
$('#listNoneItem').hide();return;case"password":panelToShow=$('#authOptionPass_panel');$('#listNoneItem').show();break;case"question":panelToShow=$('#authOptionQA_panel');$('#listNoneItem').show();$('#methodMetaTips').hide();break;case"google":panelToShow=$('#authOptionGoogle_panel');this.model.set({authMethod:'thirdParty',authService:'google'});$('#listNoneItem').show();break;case"twitter":panelToShow=$('#authOptionTwitter_panel');this.model.set({authMethod:'thirdParty',authService:'twitter'});$('#listNoneItem').show();break;case"notwitter":panelToShow=$('#authOptionNoTwitter_panel');$('#listNoneItem').show();break;case"native":panelToShow=$('#authOptionNative_panel');$('#listNoneItem').show();break;case"phone":panelToShow=$('#authOptionPhone_panel');$('#listNoneItem').show();break;case"email":if(lockifyGlobals.enableIntEmail){this.model.set({authMethod:'intEmail',authService:'google'});}else{this.model.set({authMethod:'email',authService:''});}
panelToShow=$('#authOptionEmail_panel');$('#listNoneItem').show();break;}
if(panelToShow===null){return;}
if($('#publicAuthText').length){$('#publicAuthText').hide();}
$('#data').css('height','85px');if(panelVisible){$('.authOptionPanel').hide();panelToShow.show();setTimeout(function(){panelToShow.find('input')[0].focus();},1);}else{$('.authOptionPanel').hide();this.authSelect.disableKeys();var authSelect=this.authSelect;panelToShow.slideDown(this.defaultSlideDuration,function(){authSelect.enableKeys();if($.isFunction(postShowCallback)){postShowCallback();}
panelToShow.find('input')[0].focus();});}
panelToShow.trigger("show");},handleSelectEnter:function(event){},handleSelectLeave:function(event){},handleSelectClick:function(event){},handleSelectIconEnter:function(event){},handleSelectIconLeave:function(event){},handleSelectIconFocus:function(event){},handleSelectIconBlur:function(event){},handleCancelAuth:function(event){this.model.clearAuthAttributes();$('#generateLink').click();},reset:function(){this.authSelect.reset();},clearErrors:function(){AuthMethodView.__super__.clearErrors();$('#authDiv #cancelAuthMessage').appendTo($('#stepThree')).hide();},handleAuthErrorOnly:function(){$('#authHeader > #cancelAuthMessage').clone().appendTo($('#authDiv .validationErrors:visible:last')).css('display','inline');$("#cancelAuthMessage").prev(".error").css("display","inline");}});