var Html5FileReaderView=BaseFileReaderView.extend({defaults:{enableDnD:false},events:{"change #html5FileReaderInput":"handleChange"},initialize:function(options){this.options=$.extend(this.defaults,options);_.bindAll(this,['gatherFiles']);_.bindAll(this,['drop']);_.bindAll(this,['dropNotAllowed']);var fileAvailable;if(document.lockifyUserEntryDefaults!==undefined){fileAvailable=document.lockifyUserEntryDefaults.attributes.allow_files;}else if(uu!==undefined){fileAvailable=uu.get('allowFiles');}else{fileAvailable=false;}
if(this.options.enableDnD&&$.browser.chrome&&fileAvailable){$('body').bind('drop',this.drop);$('body').bind('dragover',this.dragBodyOver);$('body').bind('dragleave',this.dragBodyLeave);}else{$('body').bind('drop',this.dropNotAllowed);}
_.bindAll(this,['handleCameraClick']);$('#incPhotoIcon').bind('click',this.handleCameraClick);$(this.el).removeClass('defaultHide');BaseFileReaderView.prototype.initialize.call(this);lockifyUtils.setupQtips('#html5FileReader',{my:'center left',at:'center right'},{corner:'center left'});$('#html5FileReader').click(function(){$(this).qtip('hide');});},fileReader:function(){return this;},dragBodyOver:function(e){e.preventDefault();$('#html5dragBorder').show();$('#dragTarget').removeClass('defaultHide').addClass('dragActive');},dragBodyLeave:function(){$('#html5dragBorder').hide();$('#dragTarget').addClass('defaultHide').removeClass('dragActive');},dropNotAllowed:function(event){event.preventDefault();event=event.originalEvent;$("#fileNotAllowedDialog").dialog($.extend({},dialogOptions,{modal:false,dialogClass:'blip'}));setTimeout(function(){$("#fileNotAllowedDialog").dialog('close');},2500);return;},drop:function(event){this.dragBodyLeave();event.preventDefault();event=event.originalEvent;if(!event.dataTransfer.files.length){$("#noFilesDroppedDialog").dialog(dialogOptions);return;}
var items=event.dataTransfer.items;if(typeof items[0].webkitGetAsEntry=="function"){var isDirArr=$.map(items,function(val,i){try{return val.webkitGetAsEntry().isDirectory;}catch(x){return false;}});if($.inArray(true,isDirArr)!=-1){$("#noDirsDialog").dialog(dialogOptions);return;}}
this.commonHandleChange(event.dataTransfer.files);$('#dragTarget').addClass('defaultState').removeClass('dropState');},handleChange:function(event){this.commonHandleChange(event.target.files);},commonHandleChange:function(files){var curTotal=lockify.index.entry.gatherFileMetadata().length;var newCount=files.length;var availFileSlots=lockifyIndexGlobals.maxFilesPerLink-curTotal;if(availFileSlots<newCount){this.tooManyFilesHandler(newCount,curTotal);return;}
var i,file;for(i=0;i<files.length;i++){file=files[i];var curBytes=this.collection.totalNumBytes();var numBytesRemaining=this.options.maxFileKb*1024-curBytes;if(file.size>numBytesRemaining){this.fileTooLargeHandler(file.size,curBytes,newCount);return;}
this.addFile(file);BaseFileReaderView.prototype.addFile.call(this,file.name,file.size);}},fileRefs:function(){return this.collection;},disableButton:function(){$('#html5FileReaderInput').disable();$(this.el).hide();},enableButton:function(){$('#html5FileReaderInput').enable();},gatherFiles:function(){return $.map(this.collection.models,function(item,index){return{'filename':item.get('filename'),'size':item.get('numBytes'),'index':index,'asyncReader':item.get('asyncReader')};});},addFile:function(file,blocksize){var self=this;blocksize=blocksize||16384;(function(){var offset=0,nextBlock=null,callback=null,fireCallback=function(){var oldCallback=callback,bytes=[],i,bytesArrayView;if(typeof(nextBlock)==='string'){for(i=0;i<nextBlock.length;i++){bytes.push(nextBlock.charCodeAt(i));}}
else{bytesArrayView=new Uint8Array(nextBlock);for(i=0;i<bytesArrayView.length;i++){bytes.push(bytesArrayView[i]);}}
callback=nextBlock=null;fetchNextBlock();oldCallback(bytes);},fetchNextBlock=function(){var readerAPI=new FileReader(),blob=null;readerAPI.onloadend=function(evt){if(evt.target.readyState===FileReader.DONE){nextBlock=evt.target.result;if(callback){fireCallback();}}};if(file.mozSlice){blob=file.mozSlice(offset,offset+blocksize);}
else if(file.webkitSlice){blob=file.webkitSlice(offset,offset+blocksize);}
else{if(typeof window.webkitRequestFileSystem=='undefined'){blob=file.slice(offset,blocksize);}else{blob=file.slice(offset,offset+blocksize);}}
if(readerAPI.readAsArrayBuffer){readerAPI.readAsArrayBuffer(blob);}
else{readerAPI.readAsBinaryString(blob);}
offset+=blocksize;};fetchNextBlock();self.collection.add({numBytes:file.size,filename:file.name,displaySize:lockifyUtils.formatFileSize(file.size),asyncReader:function(newCallback){callback=newCallback;if(nextBlock!==null){fireCallback();}}});})();},remove:function(model,models,options){BaseFileReaderView.prototype.remove.call(this,model,models,options);if(this.fileRefs.length<lockifyIndexGlobals.maxFilesPerLink){this.enableButton();}
if(fileListView.fileCount()<=1){$("#addedDocsDiv").slideUp(function(){$("#dataContainer").removeClass("fileAdded");});$(".saveFileMetadataContainer label").addClass('disabled');$('#saveFileMetadata').prop('disabled',true);}
$('#html5FileReader').show();},handleCameraClick:function(e){chrome.permissions.request({permissions:["videoCapture"]},function(granted){if(lockifyGlobals.client_type=="chrome_ext"||granted){$("#cameraOverlay").removeClass('defaultHide');new CameraCaptureView({});}});}});