var PlainInputView=BaseEncryptInputView.extend({params_defaults:{"maskOnBlur":true,"lorem":null},events:{"mouseover #data":"handleMouseover","mouseout #data":"handleMouseout","click .dataOverlayTextMask":"handleOverlayClick","click #data":"handleClick","focus #data":"handleFocus","blur #data":"handleBlur","change #maskToggle":"handleMaskToggle","keyup #data":"updateCharCount","paste #data":"updateCharCount","cut #data":"updateCharCount","input #data":"updateCharCount","click #toggleBarToggle":"handleBarToggle","click #expressFileRegister":"handleExpressFileRegister"},enableMask:true,initialize:function(options){this.params_defaults.lorem=new LoremModel();this.params=$.extend(this.params_defaults,options.params);PlainInputView.__super__.initialize();$('.confirmDestination').waitButton();if(window.location.hash.substr(0,8)=='#!input!'){this.model.set({plaintext:decodeURIComponent(window.location.hash.substr(8))});}
$('#data').data("maxLength",lockifyIndexGlobals.maxMessageCharLength);_.bindAll(this,['reset']);$(document).bind('formReset',this.reset);_.bindAll(this,['updateCharCount']);this.model.bind("validationError",this.handleValidationError);$("a:not(.noExitLink)").click(function(){if($("#firstScreen").is(":hidden")||$('#data').val().length||$('#addedDocsDiv').is(':visible')){var obuHandler=null;if(lockifyUtils.isOnBeforeUnloadMsgSet()){obuHandler=window.onbeforeunload;}
lockifyUtils.setOnBeforeUnloadMsg(null);var destinationURL=$(this).attr('href');$(".confirmDestination").click(function(){window.location=destinationURL;});$("#exitPageDialog").dialog($.extend({},dialogOptions,{close:function(e){if($(e.currentTarget)!==$("#confirmDesitination")){lockifyUtils.setOnBeforeUnloadMsg(obuHandler);}}}));return false;}});if($('#data').length){setTimeout(function(){if($('.ui-widget-overlay:visible').length==0){$('#data').focus();}},500);}},handleOverlayClick:function(){$('#data').focus();},handleClick:function(e){if($('#dataOverlayText').is(':visible')){if(e.stopImmediatePropagation){e.stopImmediatePropagation();}
e.cancelBubble=true;$('#data').triggerHandler('focus');}},handleMouseover:function(){if($('#initialDataOverlayText').is(':visible')){$('#initialDataOverlayText').addClass('dataOverlayTextMask-hover');}
if($('#dataOverlayText').is(':visible')){$('#dataOverlayText').addClass('dataOverlayTextMask-hover');}},handleMouseout:function(){$('#dataOverlayText').removeClass('dataOverlayTextMask-hover');$("#initialDataOverlayText").removeClass('dataOverlayTextMask-hover');},handleFocus:function(){$('#dataOverlayText').removeClass('dataOverlayTextMask-hover');$('#data').removeClass('data-blur').addClass('data-focus');$("#dataBottomBar").addClass('data-input-focus').removeClass('data-input-blur');if(this.model.get('plaintext')!==""){$("#dataOverlayText").addClass('hiddenOverlay');$('#data').val(this.model.get('plaintext')).removeClass('data-blur').addClass('data-focus');}
setTimeout(function(){$('#data').scrollTop(10000);},10);},copyPlaintextToModel:function(){var val=$('#data').val();if(val.length&&!val.match(/[^\s\t\n\u000B\f\r]/)){val="";$('#data').val(val);}
this.model.set({plaintext:val,msgLength:val.length});return true;},handleBlur:function(event){var val=this.model.get('plaintext');if(val.toLowerCase()=='lorem')
{this.params.lorem.fetch({success:function(model){$("#data").val('');while($("#data").val().length<$("#data").data("maxLength")){$("#data").val($("#data").val()+model.get('lorem'));}
$("#data").val($("#data").val().substring(0,$("#data").data("maxLength")));$("#data").keyup();$(document).trigger('cryptoAssetLengthChanged');$("#data").blur();},error:function(req,textStatus,errorThrown){$("#divInput").append(req.responseText);}});this.params.lorem.set('lorem','');return;}
if(!this.copyPlaintextToModel()){return true;}
if($('#data').val()!==""){$('#data').removeClass('data-focus').addClass('data-blur');$("#dataBottomBar").addClass('data-input-blur').removeClass('data-input-focus');$('#dataOverlayText').removeClass('dataOverlayText-hover').removeClass('hiddenOverlay');}else{$("#initialDataOverlayText").removeClass('hiddenOverlay');$('#dataOverlayText').removeClass('dataOverlayText-hover').addClass('hiddenOverlay');$('#dataCharCount').css('visibility','hidden');$("#dataBottomBar").removeClass('data-input-blur').removeClass('data-input-focus');}
if(!this.params.maskOnBlur){return;}},updateCharCount:function(){$("#initialDataOverlayText").addClass('hiddenOverlay');this.copyPlaintextToModel();var theModel=this.model;$('#data').animate({opacity:1.0},1,function(){var currentLength=theModel.get('plaintext').length;var messageLinkLength=theModel.totalDataLinkLength().toString();if(messageLinkLength>lockifyIndexGlobals.linkWarningLength){$("#advUi #embedMessage_warning").css('display','inline-block').trigger('show');}else{$("#advUi #embedMessage_warning").hide().trigger('hide');}
var messageDataLength=theModel.totalDataLength().toString().replace(/([0-9]+)([0-9]{3})$/,'$1,$2');$(document).trigger('cryptoAssetLengthChanged',messageDataLength);var remainingChars=lockifyUtils.numberWithCommas(($('#data').data('maxLength')-currentLength));$('#dataCharCount').text(remainingChars);$("#dataCharCount").css("visibility","visible");$('#dataCharCount').toggleClass('dataCharCount-excessive',currentLength>$('#data').data('maxLength'));});},handleMaskToggle:function(){this.enableMask=!this.enableMask;$('#data').focus();if(this.enableMask){$('#data').blur();}},handleBarToggle:function(){$("#toggleBar").slideToggle();$("#toggleBarToggle").children(".hideTrigger").toggle();$("#toggleBarToggle").children(".showTrigger").toggle();},handleExpressFileRegister:function(){$('.expressRegister').click();},reset:function(){$('#data').focus().val('').blur();},handleValidationError:function(type,msg){if(type==='plainInput'){PlainInputView.__super__.appendError($("#dataContainer > .validationErrors"),msg,$('#data'));$("#dataContainer").addClass("inputError");}}});