var NicknameView=Backbone.View.extend({defaults:{saveBtnEl:null},events:{'focus .nickname':'handleFocus','blur .nickname':'handleBlur','change .nickname':'handleChange','keyup .nickname':'updateCharCount','paste .nickname':'updateCharCount','cut .nickname':'updateCharCount','input .nickname':'updateCharCount',},lastSavedVal:null,initialize:function(options){this.options=$.extend({},this.defaults,options||{});_.bindAll(this,['handleKeyupEnabled']);_.bindAll(this,['handleKeyupDisabled']);_.bindAll(this,['handleSaveSuccess']);_.bindAll(this,['disableNicknameButton']);_.bindAll(this,['handleClick']);_.bindAll(this,['deleteNickname']);this.nicknameInput=this.$el.find('.nickname');this.nickCharCount=this.$el.find('.nickCharCount');this.nicknameWrap=this.$el.find('.nicknameWrapper');if(this.options.saveBtnEl){this.btnSaveNickname=this.options.saveBtnEl;}else{this.btnSaveNickname=this.$el.find('.btnSaveNickname');}
this.btnSaveNickname.unbind('click');if(!this.btnSaveNickname.is(':disabled')){this.btnSaveNickname.click(this.handleClick);}
if(this.options.delBtnEl){this.options.delBtnEl.unbind('click');this.options.delBtnEl.click(this.deleteNickname);}
if(this.options.cancelBtnEl){this.options.cancelBtnEl.unbind('click');this.options.cancelBtnEl.click(this.handleCancelBtnClick);}
this.disableNicknameButton();this.oldValue=this.model.get('nickname');var val=this.oldValue;if(val){this.nicknameInput.val(val);this.lastSavedVal=val;this.handleSaveSuccess();this.updateCharCount();}else{this.nickCharCount.text('');}},handleFocus:function(event){this.nicknameWrap.addClass('focus');},handleBlur:function(event){this.nicknameWrap.removeClass('focus');var sanVal=lockifyUtils.sanitize($(event.target).val());if($(event.target).val()!=sanVal){lockifyUtils.showMessageDialog("Characters replaced for security.");}
$(event.target).val(sanVal);if($(event.target).val()===''){this.nickCharCount.text('');this.disableNicknameButton();this.btnSaveNickname.children('.text').text('Save');}},handleClick:function(){var val=$.trim(this.nicknameInput.val());var self=this;this.model.set('nickname',val);var pickedFields=_.pick(this.model.attributes,'dataHash','nickname','publicId');if(this.model.has('cryptoAssets')){pickedFields.adminCredHash=this.model.get("cryptoAssets")["adminCredHash"];}
this.model.save(pickedFields,{patch:true,success:function(model,json){self.lastSavedVal=val;self.handleSaveSuccess();self.handleNicknameSaved('nickname-saved',val);self.model.trigger('changed:nickname');},error:function(model,json){self.model.set('nickname',self.oldValue);self.model.trigger('changed:nickname');}});},deleteNickname:function(){this.nicknameInput.val('');this.handleClick();},handleSaveSuccess:function(json){this.btnSaveNickname.children('.text').text(lockifyGlobals.savedMsg);this.nicknameInput.addClass('match');this.disableNicknameButton();},enableNicknameButton:function(){this.btnSaveNickname.removeClass('disabled').prop('disabled',false).children('.text').text('Save now');this.nicknameInput.unbind('keyup paste cut input');this.nicknameInput.bind('keyup paste cut input',this.handleKeyupEnabled);this.nicknameInput.removeClass('match');this.btnSaveNickname.click(this.handleClick);},handleKeyupEnabled:function(event){var val=$(event.target).val();if(this.options.delBtnEl&&(val==this.lastSavedVal||$.trim(val).length===0)){this.disableNicknameButton();this.nicknameInput.addClass('match');return;}
if(event.keyCode==13){this.btnSaveNickname.click();}},disableNicknameButton:function(){this.btnSaveNickname.addClass('disabled').prop('disabled',true);this.nicknameInput.unbind('keyup cut input');this.nicknameInput.bind('keyup cut input',this.handleKeyupDisabled);this.btnSaveNickname.unbind('click',this.handleClick);},handleKeyupDisabled:function(event){var val=$(event.target).val();if(this.lastSavedVal==null&&val.length===0){return false;}
if(val!=this.lastSavedVal&&$.trim(val).length>=0){this.enableNicknameButton();}
return null;},handleChange:function(){this.model.set({nickname:lockifyUtils.sanitize(this.nicknameInput.val())});},updateCharCount:function(){var self=this;setTimeout(function(){var currentLength=self.nicknameInput.val().length;var remainingChars=(self.nicknameInput.data('maxLength')-currentLength).toString();self.nickCharCount.text(remainingChars);self.nickCharCount.toggleClass('dataCharCount-excessive',currentLength>self.nickCharCount.data('maxLength'));if(remainingChars==self.nicknameInput.data('maxLength')){self.nickCharCount.hide();}else{self.nickCharCount.show();}},1);},handleNicknameSaved:function(event,val){var trig=$('#nicknameDialog').data('triggerElem');if(trig){if(trig.hasClass('addNickname')){trig.siblings('.publicIdCell').after('<span class="nicknameCell" data-nickname="'+escape(val)+'">'+val+'</span>');trig.parent().removeClass('noNickname');trig.remove();}else{if(!val||val===''){trig.siblings('.publicIdCell').after(" <span class='addNickname'>Add label</span>");trig.parent().addClass('noNickname');trig.remove();}else{trig.text(val);trig.data("nickname",escape(val));}}
$('#nicknameDialog').dialog('close');var wid=getTruncWidth();$('.nicknameCell').truncate({width:wid,addtitle:'true',addclass:'truncated',token:'<span class="elipsis">&#133;</span>'});}
trig=$('#nicknameDialog').data('triggerElemNew');if(trig){$('#nicknameDialog').dialog('close');}},handleCancelBtnClick:function(){$('#nicknameDialog').dialog('close');}});